export const UI_SUPPLEMENT = {
  "en": {
    "fullName": "Full name",
    "yourFullName": "Your full name",
    "mobileNumber": "Mobile number",
    "tenDigitMobile": "10-digit mobile",
    "emailOptional": "Email (optional)",
    "emailPlaceholder": "you@example.com",
    "addressCityOptional": "Address / city (optional)",
    "whereAgenciesReach": "Where agencies can reach you",
    "idType": "ID type",
    "voterId": "Voter ID",
    "pan": "PAN",
    "drivingLicence": "Driving licence",
    "idNumber": "ID number",
    "enterIdNumber": "Enter ID number",
    "oneTimePassword": "One-time password",
    "otpPlaceholder": "6-digit OTP",
    "sending": "Sending…",
    "sendOtp": "Send OTP",
    "checking": "Checking…",
    "verifyOtp": "Verify OTP",
    "phoneVerified": "Phone verified",
    "reportAnonymously": "Report anonymously",
    "noIdentityRequired": "No name, phone, or ID required. You will receive a tracking ID.",
    "select": "Select",
    "whoAsked": "Who asked for or took the bribe?",
    "centralEmployee": "Central government employee / PSU / bank",
    "stateEmployee": "State government or local body employee",
    "policeVigilance": "Police or vigilance personnel",
    "onlineDemand": "Online / phone / UPI demand",
    "notSure": "Not sure",
    "officialName": "Official's name (if known)",
    "officialNamePlaceholder": "e.g. Ramesh Verma",
    "designation": "Designation",
    "designationPlaceholder": "e.g. Clerk, Inspector",
    "departmentOffice": "Department / office",
    "departmentPlaceholder": "e.g. Regional Passport Office",
    "officeAddress": "Office address / area",
    "officeAddressPlaceholder": "Building, street, city or district",
    "serviceWork": "What service or work was involved?",
    "servicePlaceholder": "e.g. Building permit, licence renewal, pension file",
    "whatDemanded": "What was demanded",
    "amountPaid": "Amount demanded / paid (₹)",
    "amountPlaceholder": "e.g. 2000",
    "paymentForm": "Form of payment",
    "cash": "Cash",
    "upi": "UPI / online transfer",
    "bankTransfer": "Bank transfer",
    "giftGoods": "Gift or goods",
    "favourBenefit": "Favour or other benefit",
    "demandMaker": "Who made the demand?",
    "officialPersonally": "The official personally",
    "intermediary": "An intermediary / agent / middleman",
    "both": "Both",
    "witnessDetails": "Witnesses / intermediary details",
    "witnessPlaceholder": "Names and contact, if any",
    "dateDemand": "Date of demand",
    "timeApprox": "Time (approx.)",
    "placeDemand": "Place where the demand was made",
    "placePlaceholder": "e.g. Counter 4, office gate, over phone",
    "factsLabel": "What the official said or did (facts only)",
    "factsPlaceholder": "Describe exactly what was said or done, in order.",
    "evidenceLabel": "Evidence and reference details",
    "evidencePlaceholder": "Messages, phone numbers, emails, notices, receipts, screenshots or transaction details",
    "referenceLabel": "Application / file / licence reference number",
    "referencePlaceholder": "e.g. Application No. 12345/2026",
    "finalReview": "Final review",
    "analysing": "Analysing…",
    "exactWebsite": "Find exact website",
    "runAssistant": "Run the AI assistant before submitting",
    "submitComplaint": "Submit complaint",
    "continue": "Continue",
    "back": "Back",
    "securityCheck": "Security check: enter 7 + 4",
    "successRedirect": "Your complaint was recorded. Opening the exact official destination…",
    "openOfficial": "Open exact official website",
    "seeOfficer": "See officer above",
    "officialDestination": "Choose the correct official destination",
    "education": "Education",
    "backPortal": "Back to portal",
    "useGuide": "Use this as a guide",
    "safetyReminder": "Safety reminder"
  },
  "as": {
    "fullName": "সম্পূৰ্ণ নাম",
    "yourFullName": "আপোনাৰ সম্পূৰ্ণ নাম",
    "mobileNumber": "ম'বাইল নম্বৰ",
    "tenDigitMobile": "10-অংকৰ ম'বাইল",
    "emailOptional": "ইমেইল (বিকল্প)",
    "emailPlaceholder": "you@example.com",
    "addressCityOptional": "ঠিকনা / চহৰ (বিকল্প)",
    "whereAgenciesReach": "সংস্থাসব আপোনালোক ক'ত যোগাযোগ কৰিব পাৰে",
    "idType": "পচ যোগাযোগৰ ধৰণ",
    "voterId": "মাহাজনা কাৰ্ড",
    "pan": "PAN",
    "drivingLicence": "ড্ৰাইভিং লাইচেঞ্চ",
    "idNumber": "ID নম্বৰ",
    "enterIdNumber": "ID নম্বৰ প্ৰবিষ্ট কৰক",
    "oneTimePassword": "একবাৰীয়া পাছৱৰ্ড",
    "otpPlaceholder": "6-অংকৰ OTP",
    "sending": "প্ৰেৰণ কৰা হৈছে…",
    "sendOtp": "OTP পঠিওৱক",
    "checking": "পৰীক্ষা কৰা হৈছে…",
    "verifyOtp": "OTP নিশ্চিত কৰক",
    "phoneVerified": "ফোন নিশ্চিত কৰা হৈছে",
    "reportAnonymously": "নাম নঘোষণা কৰি অভিযোগ দাখিল কৰক",
    "noIdentityRequired": "নাম, ফোন, বা IDৰ প্ৰয়োজন নাই। আপোনাক এটা ট্রেকিং ID প্ৰদান কৰা হ'ব।",
    "select": "নির্বাচন কৰক",
    "whoAsked": "দেনাৰ দাবী কোনে কৰিছিল বা ললে?",
    "centralEmployee": "কেন্দ্ৰীয় চৰকাৰী কৰ্মচাৰী / PSU / বেংক",
    "stateEmployee": "ৰাজ্য চৰকাৰী বা স্থানীয় সংস্থাৰ কৰ্মচাৰী",
    "policeVigilance": "পৰ্যবেক্ষণ বা আৰক্ষী কৰ্মী",
    "onlineDemand": "অনলাইন / ফোন / UPI দাবী",
    "notSure": "নिश्चয় নহয়",
    "officialName": "অফিচিয়েলৰ নাম (জানিলে)",
    "officialNamePlaceholder": "উদা. ৰমেশ বৰ্মা",
    "designation": "পদবী",
    "designationPlaceholder": "উদা. Clerk, Inspector",
    "departmentOffice": "বিভাগ / কাৰ্যালয়",
    "departmentPlaceholder": "উদা. Regional Passport Office",
    "officeAddress": "কাৰ্যালয় ঠিকনা / এলাকা",
    "officeAddressPlaceholder": "ভৱন, পথ, চহৰ বা জিলিল",
    "serviceWork": "কোন সেৱা বা কাম জড়িত আছিল?",
    "servicePlaceholder": "উদা. Building permit, licence renewal, pension file",
    "whatDemanded": "কি দাবী কৰা হৈছিল",
    "amountPaid": "দাবী / দিয়া ৰাশি (₹)",
    "amountPlaceholder": "উদা. 2000",
    "paymentForm": "পেমেন্টৰ প্ৰকাৰ",
    "cash": "কেছ",
    "upi": "UPI / অনলাইন স্থানান্তৰ",
    "bankTransfer": "বেংক স্থানান্তৰ",
    "giftGoods": "উপহাৰ বা সামগ্ৰী",
    "favourBenefit": "অনুকম্পা বা অন্যান্য সুবিধা",
    "demandMaker": "দাবী কোনে কৰিছিল?",
    "officialPersonally": "অফিচিয়েল নিজে",
    "intermediary": "এজন মধ্যস্থ / এজেঞ্জী / মধ্যমান",
    "both": "উভয়ে",
    "witnessDetails": "সাক্ষী / মধ্যস্থৰ বিৱৰণ",
    "witnessPlaceholder": "নাম আৰু যোগাযোগ, যদি থাকে",
    "dateDemand": "দাবীৰ তাৰিখ",
    "timeApprox": "সময় (আনুমানিক)",
    "placeDemand": "দাবী কৰা স্থান",
    "placePlaceholder": "উদা. কাউণ্টাৰ 4, কাৰ্যালয়ৰ গেট, ফোনত",
    "factsLabel": "অফিচিয়েলয়ে কি ক'লে বা কৰিলে (কেৱল তথ্য)",
    "factsPlaceholder": "ঠিক কি ক'োৱা হৈছিল বা কৰা হৈছিল, ক্ৰমানুসাৰে বৰ্ণনা কৰক।",
    "evidenceLabel": "প্ৰমাণ আৰু তথ্যৰ বিৱৰণ",
    "evidencePlaceholder": "মেছেজ, ফোন নম্বৰ, ইমেইল, নোটিছ, ৰিছিট, স্ক্ৰীণশ্বট বা লেনদেনৰ বিৱৰণ",
    "referenceLabel": "আবেদন / ফাইল / লাইচেঞ্চ ৰেফাৰেন্স নম্বৰ",
    "referencePlaceholder": "উদা. Application No. 12345/2026",
    "finalReview": "চূড়ান্ত পৰ্যালোচনা",
    "analysing": "বিশ্লেষণ কৰিছে…",
    "exactWebsite": "ঠিক কোন ৱেবছাইটটো finde কৰক",
    "runAssistant": "দাখিল কৰাৰ আগেয়ে AI সহায়ক চলাওক",
    "submitComplaint": "অভিযোগ দাখিল কৰক",
    "continue": "আগবঢ়াওক",
    "back": "পিছলৈ",
    "securityCheck": "নিরাপত্তা পৰীক্ষা: 7 + 4 সোমাব",
    "successRedirect": "আপোনাৰ অভিযোগ দাখিল কৰা হৈছে। ঠিক কাৰ্যালয় উদ্দেশ্য খোলা হৈছে…",
    "openOfficial": "ঠিক কৰ্তৃপক্ষৰ ৱেবছাইট খোলক",
    "seeOfficer": "উল্লেখিত কৰ্মচাৰী চাওক",
    "officialDestination": "সঠিক কাৰ्यालय পঠিয়াবলৈ নিৰ্বাচন কৰক",
    "education": "শিক্ষা",
    "backPortal": "পৰ্টেললৈ উভতি যাওক",
    "useGuide": "ইয়াক এবিধ পথপ্ৰদৰ্শক হিচাপে ব্যৱহাৰ কৰক",
    "safetyReminder": "সুৰক্ষাৰ বাবে স্মৰণ"
  },
  "bn": {
    "fullName": "পুরো নাম",
    "yourFullName": "আপনার পুরো নাম",
    "mobileNumber": "মোবাইল নম্বর",
    "tenDigitMobile": "10-অঙ্কের মোবাইল",
    "emailOptional": "ইমেইল (ঐচ্ছিক)",
    "emailPlaceholder": "you@example.com",
    "addressCityOptional": "ঠিকানা / শহর (ঐচ্ছিক)",
    "whereAgenciesReach": "সংস্থাগুলি আপনাকে কোথায় পৌঁছাতে পারে",
    "idType": "আইডি ধরন",
    "voterId": "ভোটার আইডি",
    "pan": "PAN",
    "drivingLicence": "ড্রাইভিং লাইসেন্স",
    "idNumber": "আইডি নম্বর",
    "enterIdNumber": "আইডি নম্বর লিখুন",
    "oneTimePassword": "ওয়ান-টাইম পাসওয়ার্ড",
    "otpPlaceholder": "6-অঙ্কের OTP",
    "sending": "পাঠানো হচ্ছে…",
    "sendOtp": "OTP পাঠান",
    "checking": "পরীক্ষা করা হচ্ছে…",
    "verifyOtp": "OTP যাচাই করুন",
    "phoneVerified": "ফোন যাচাই হয়েছে",
    "reportAnonymously": "নাম প্রকাশ না করে প্রতিবেদন করুন",
    "noIdentityRequired": "নাম, ফোন বা আইডির প্রয়োজন নেই। আপনি একটি ট্র্যাকিং আইডি পাবেন।",
    "select": "নির্বাচন করুন",
    "whoAsked": "কারা ঘুষ চাইছিল বা নিয়েছিল?",
    "centralEmployee": "কেন্দ্রীয় সরকারি কর্মী / PSU / ব্যাংক",
    "stateEmployee": "রাজ্য সরকার বা স্থানীয় সংস্থার কর্মী",
    "policeVigilance": "পুলিশ বা সুরক্ষা কর্মী",
    "onlineDemand": "অনলাইন / ফোন / UPI দাবি",
    "notSure": "নিশ্চিত নই",
    "officialName": "কর্তৃপক্ষের নাম (যদি জানা থাকে)",
    "officialNamePlaceholder": "উদা. Ramesh Verma",
    "designation": "পদবী",
    "designationPlaceholder": "উদা. Clerk, Inspector",
    "departmentOffice": "বিভাগ / অফিস",
    "departmentPlaceholder": "উদা. Regional Passport Office",
    "officeAddress": "অফিস ঠিকানা / এলাকা",
    "officeAddressPlaceholder": "ইমারত, রাস্তা, শহর বা জেলা",
    "serviceWork": "কোন সেবা বা কাজ জড়িত ছিল?",
    "servicePlaceholder": "উদা. Building permit, licence renewal, pension file",
    "whatDemanded": "কি দাবি করা হয়েছিল",
    "amountPaid": "দাবি করা/প্রদত্ত পরিমাণ (₹)",
    "amountPlaceholder": "উদা. 2000",
    "paymentForm": "পেমেন্টের ধরন",
    "cash": "নগদ",
    "upi": "UPI / অনলাইন স্থানান্তর",
    "bankTransfer": "ব্যাংক ট্রান্সফার",
    "giftGoods": "উপহার বা জিনিস",
    "favourBenefit": "পছন্দ বা অন্যান্য সুবিধা",
    "demandMaker": "দাবি কে করেছে?",
    "officialPersonally": "কর্তৃপক্ষ নিজে",
    "intermediary": "মধ্যস্থ / এজেন্ট / মধ্যস্বত্তা",
    "both": "উভয়ই",
    "witnessDetails": "সরকারী সাক্ষী / মধ্যস্থের বিবরণ",
    "witnessPlaceholder": "নাম এবং যোগাযোগ, থাকলে",
    "dateDemand": "দাবির তারিখ",
    "timeApprox": "সময় (প্রায়)",
    "placeDemand": "যেখানে দাবি করা হয়েছিল",
    "placePlaceholder": "উদা. কাউন্টার 4, অফিস গেট, ফোনে",
    "factsLabel": "কর্তৃপক্ষ কি বলেছিল বা করেছিল (শুধু তথ্য)",
    "factsPlaceholder": "যা বলা বা করা হয়েছিল ঠিক তা ক্রমানুসারে বর্ণনা করুন।",
    "evidenceLabel": "প্রমাণ ও রেফারেন্সের বিবরণ",
    "evidencePlaceholder": "মেসেজ, ফোন নম্বর, ইমেইল, নোটিস, রসিদ, স্ক্রিনশট বা লেনদেনের বিবরণ",
    "referenceLabel": "আবেদন / ফাইল / লাইসেন্স রেফারেন্স নম্বর",
    "referencePlaceholder": "উদা. Application No. 12345/2026",
    "finalReview": "চূড়ান্ত পর্যালোচনা",
    "analysing": "বিশ্লেষণ করা হচ্ছে…",
    "exactWebsite": "ঠিক কোন ওয়েবসাইট",
    "runAssistant": "জমা দেওয়ার আগে AI সহকারী চালান",
    "submitComplaint": "অভিযোগ জমা করুন",
    "continue": "চালিয়ে যান",
    "back": "ফিরে যান",
    "securityCheck": "নিরাপত্তা পরীক্ষা: 7 + 4 লিখুন",
    "successRedirect": "আপনার অভিযোগ রেকর্ড করা হয়েছে। সঠিক সরকারি গন্তব্য খুলছে…",
    "openOfficial": "সঠিক সরকারি ওয়েবসাইট খুলুন",
    "seeOfficer": "উপরে থাকা কর্মকর্তাকে দেখুন",
    "officialDestination": "সঠিক সরকারি গন্তব্য নির্বাচন করুন",
    "education": "শিক্ষা",
    "backPortal": "পোর্টালে ফিরে যান",
    "useGuide": "এটি একটি গাইড হিসেবে ব্যবহার করুন",
    "safetyReminder": "নিরাপত্তার স্মরণ"
  },
  "brx": {
    "fullName": "फुल नाव",
    "yourFullName": "अहाँर फुल नाव",
    "mobileNumber": "मोबाइल नंबर",
    "tenDigitMobile": "10-अंके मोबाइल",
    "emailOptional": "ईमेल (वैकल्पिक)",
    "emailPlaceholder": "you@example.com",
    "addressCityOptional": "पता / सहर (वैकल्पिक)",
    "whereAgenciesReach": "संस्था सभ अहाँलाइ हहि ठाँ संपर्क करि पाए",
    "idType": "ID प्रकार",
    "voterId": "मतदाता ID",
    "pan": "PAN",
    "drivingLicence": "ड्राइविंग लाइसेंस",
    "idNumber": "ID नंबर",
    "enterIdNumber": "ID नंबर दाबि करु",
    "oneTimePassword": "एक-बेर पासवर्ड",
    "otpPlaceholder": "6-अंके OTP",
    "sending": "पठाउतәсәй…",
    "sendOtp": "OTP पठाउ",
    "checking": "जाँच करत…",
    "verifyOtp": "OTP सत्यापित करु",
    "phoneVerified": "फोन सत्यापित भ'गेल",
    "reportAnonymously": "नाम बिना रिपोर्ट करु",
    "noIdentityRequired": "नाम, फोन, वा ID आवश्यक नाइ। अहाँक ट्रैकिंग ID देल जाएत।",
    "select": "छनु",
    "whoAsked": "घूस कुन् लेले वा मांग केल?",
    "centralEmployee": "केंद्रीय सरकारक कर्मचारी / PSU / बैंक",
    "stateEmployee": "राज्य सरकार वा स्थानीय निकायक कर्मचारी",
    "policeVigilance": "पुलिस वा निगरानी कर्मी",
    "onlineDemand": "ऑनलाइन / फोन / UPI मांग",
    "notSure": "निश्चय नाइ",
    "officialName": "अधिकारीक नाम (जानी छि त)",
    "officialNamePlaceholder": "उदा. Ramesh Verma",
    "designation": "पद",
    "designationPlaceholder": "उदा. Clerk, Inspector",
    "departmentOffice": "विभाग / कार्यालय",
    "departmentPlaceholder": "उदा. Regional Passport Office",
    "officeAddress": "कार्यालय ठेगाना / इलाका",
    "officeAddressPlaceholder": "भवन, सडक, सहर वा जिला",
    "serviceWork": "कुन सेवा वा काज संलग्न छल?",
    "servicePlaceholder": "उदा. Building permit, licence renewal, pension file",
    "whatDemanded": "की मांग कएल गेल",
    "amountPaid": "मांगल गेल / दियेल रकम (₹)",
    "amountPlaceholder": "उदा. 2000",
    "paymentForm": "भुगतानक रूप",
    "cash": "नगद",
    "upi": "UPI / ऑनलाइन ट्रांसफर",
    "bankTransfer": "बैंक ट्रांसफर",
    "giftGoods": "उपहार वा सामान",
    "favourBenefit": "किसी तरहक लाभ वा फायदा",
    "demandMaker": "मांग कियो केने?",
    "officialPersonally": "अधिकारी स्वयंप",
    "intermediary": "मध्यस्थ / एजेन्ट / दलाल",
    "both": "दूनू",
    "witnessDetails": "गवाह / मध्यस्थक विवरण",
    "witnessPlaceholder": "नाम आ संपर्क, जँ अछि",
    "dateDemand": "मांगक तिथि",
    "timeApprox": "समय (लगभग)",
    "placeDemand": "मांग कहँ कएल गेल",
    "placePlaceholder": "उदा. काउंटर 4, कार्यालय गेट, फोन पर",
    "factsLabel": "अधिकारी की कहल वा केने (केवल तथ्य)",
    "factsPlaceholder": "ठीक जे कहल वा कएल गेल, क्रममे वर्णन करू।",
    "evidenceLabel": "सबूत आ संदर्भ विवरण",
    "evidencePlaceholder": "मैसेज, फोन नंबर, ईमेल, नोटिस, रसीद, स्क्रीनशॉट वा लेनदेन विवरण",
    "referenceLabel": "आवेदन / फाइल / लाइसेंस संदर्भ संख्या",
    "referencePlaceholder": "उदा. Application No. 12345/2026",
    "finalReview": "अन्तिम समीक्षा",
    "analysing": "विश्लेषण कएल जा रहल अछि…",
    "exactWebsite": "ठीक वेबसाइट खोजू",
    "runAssistant": "जमाकरण स पहिने AI सहायक चलाउ",
    "submitComplaint": "शिकायत जमा करू",
    "continue": "जारी राखू",
    "back": "पाछाँ",
    "securityCheck": "सुरक्षा परीक्षण: 7 + 4 प्रविष्ट करू",
    "successRedirect": "अहाँक शिकायत दर्ज भ' गेल अछि। ठीक सरकारी गन्तव्य खोलल जा रहल अछि…",
    "openOfficial": "ठीक सरकारी वेबसाइट खोलू",
    "seeOfficer": "उपर कर्मचारी देखें",
    "officialDestination": "सही सरकारी गन्तव्य चुनू",
    "education": "शिक्षा",
    "backPortal": "पोर्टलक दिस पाछाँ जाउ",
    "useGuide": "ई मार्गदर्शक बला रूपमे use करू",
    "safetyReminder": "सुरक्षा स्मरण"
  },
  "doi": {
    "fullName": "पूरा नाम",
    "yourFullName": "आपका पूरा नाम",
    "mobileNumber": "मोबाइल नंबर",
    "tenDigitMobile": "10-अंकीय मोबाइल",
    "emailOptional": "इमेल (वैकल्पिक)",
    "emailPlaceholder": "you@example.com",
    "addressCityOptional": "पता / शहर (वैकल्पिक)",
    "whereAgenciesReach": "एजेंसियाँ आपको कहाँ पहुंच सकती हैं",
    "idType": "आईडी प्रकार",
    "voterId": "वोटर आईडी",
    "pan": "PAN",
    "drivingLicence": "ड्राइविंग लाइसेंस",
    "idNumber": "आईडी नंबर",
    "enterIdNumber": "आईडी नंबर दर्ज करें",
    "oneTimePassword": "वन-टाइम पासवर्ड",
    "otpPlaceholder": "6-अंकीय OTP",
    "sending": "भेजा जा रहा है…",
    "sendOtp": "OTP भेजें",
    "checking": "जाँच रहा है…",
    "verifyOtp": "OTP सत्यापित करें",
    "phoneVerified": "फ़ोन सत्यापित हुआ",
    "reportAnonymously": "गुमनाम रूप से रिपोर्ट करें",
    "noIdentityRequired": "नाम, फोन, या आईडी की जरूरत नहीं। आपको एक ट्रैकिंग आईडी मिलेगी।",
    "select": "चुनें",
    "whoAsked": "रिश्वत किसने माँगी या ली?",
    "centralEmployee": "केंद्रीय सरकार कर्मचारी / PSU / बैंक",
    "stateEmployee": "राज्य सरकार या स्थानीय निकाय कर्मचारी",
    "policeVigilance": "पुलिस या विशेष निगरानी कर्मी",
    "onlineDemand": "ऑनलाइन / फोन / UPI मांग",
    "notSure": "निश्चित नहीं",
    "officialName": "अधिकारी का नाम (यदि ज्ञात हो)",
    "officialNamePlaceholder": "उदा. Ramesh Verma",
    "designation": "पदनाम",
    "designationPlaceholder": "उदा. Clerk, Inspector",
    "departmentOffice": "विभाग / कार्यालय",
    "departmentPlaceholder": "उदा. Regional Passport Office",
    "officeAddress": "कार्यालय का पता / क्षेत्र",
    "officeAddressPlaceholder": "भवन, सड़क, शहर या जिला",
    "serviceWork": "कौन-सी सेवा या काम जुड़ा था?",
    "servicePlaceholder": "उदा. Building permit, licence renewal, pension file",
    "whatDemanded": "क्या माँगा गया था",
    "amountPaid": "माँगा गया / दिया गया राशि (₹)",
    "amountPlaceholder": "उदा. 2000",
    "paymentForm": "भुगतान का प्रकार",
    "cash": "नकद",
    "upi": "UPI / ऑनलाइन ट्रांसफर",
    "bankTransfer": "बैंक ट्रांसफर",
    "giftGoods": "उपहार या सामान",
    "favourBenefit": "अनुग्रह या अन्य लाभ",
    "demandMaker": "दावा किसने किया?",
    "officialPersonally": "अधिकारी ने स्वयं",
    "intermediary": "मध्यस्थ / एजेंट / बिचौलिया",
    "both": "दोनों",
    "witnessDetails": "गवाह / मध्यस्थ के विवरण",
    "witnessPlaceholder": "नाम और संपर्क, यदि कोई हो",
    "dateDemand": "दावे की तारीख",
    "timeApprox": "समय (अनुमानित)",
    "placeDemand": "जहाँ दावा किया गया था",
    "placePlaceholder": "उदा. Counter 4, कार्यालय गेट, फोन पर",
    "factsLabel": "अधिकारी ने क्या कहा या किया (केवल तथ्य)",
    "factsPlaceholder": "ठीक वही बताएं जो कहा या किया गया, क्रम से।",
    "evidenceLabel": "सबूत और संदर्भ विवरण",
    "evidencePlaceholder": "मैसेज, फोन नंबर, ईमेल, नोटिस, रसीद, स्क्रीनशॉट या लेनदेन विवरण",
    "referenceLabel": "आवेदन / फ़ाइल / लाइसेंस संदर्भ संख्या",
    "referencePlaceholder": "उदा. Application No. 12345/2026",
    "finalReview": "अंतिम समीक्षा",
    "analysing": "विश्लेषण कर रहे हैं…",
    "exactWebsite": "सटीक वेबसाइट खोजें",
    "runAssistant": "जमाकरण से पहले AI सहायक चलाएँ",
    "submitComplaint": "शिकायत दर्ज करें",
    "continue": "जारी रखें",
    "back": "वापस",
    "securityCheck": "सुरक्षा जांच: 7 + 4 दर्ज करें",
    "successRedirect": "आपकी शिकायत दर्ज कर ली गई है। सटीक आधिकारिक गन्तव्य खुल रहा है…",
    "openOfficial": "सटीक आधिकारिक वेबसाइट खोलें",
    "seeOfficer": "ऊपर अधिकारी देखें",
    "officialDestination": "सही आधिकारिक गन्तव्य चुनें",
    "education": "शिक्षा",
    "backPortal": "पोर्टल पर वापस",
    "useGuide": "इसे एक मार्गदर्शक के रूप में प्रयोग करें",
    "safetyReminder": "सुरक्षा अनुस्मारक"
  },
  "gu": {
    "fullName": "પૂર્ણ નામ",
    "yourFullName": "તમારું પૂર્ણ નામ",
    "mobileNumber": "મોબાઇલ નંબર",
    "tenDigitMobile": "10-અંકોનો મોબાઇલ",
    "emailOptional": "ઈમેલ (ઐચ્છિક)",
    "emailPlaceholder": "you@example.com",
    "addressCityOptional": "સરનામુ / શહેર (ઐચ્છિક)",
    "whereAgenciesReach": "સંસ્થાઓ તમને ક્યાં પહોંચાડવા શકે",
    "idType": "આઇડી પ્રકાર",
    "voterId": "વોટર આઈડી",
    "pan": "PAN",
    "drivingLicence": "ડ્રાઇવિંગ લાઇસન્સ",
    "idNumber": "આઇડી નંબર",
    "enterIdNumber": "આઇડી નંબર દાખલ કરો",
    "oneTimePassword": "વન-ટાઈમ પાસવર્ડ",
    "otpPlaceholder": "6-અંકોનું OTP",
    "sending": "પઠાવવામાં આવી રહ્યું છે…",
    "sendOtp": "OTP મોકલો",
    "checking": "ચેક કરી રહ્યો છે…",
    "verifyOtp": "OTP ચકાસો",
    "phoneVerified": "ફોન ચકાઉ થઈ ગયો છે",
    "reportAnonymously": "નામ ગુપ્ત રાખીને ફરીવાર કરો",
    "noIdentityRequired": "નામ, ફોન અથવા ID જરૂરી નથી. તમને એક ટ્રેકિંગ ID મળશે.",
    "select": "પસંદ કરો",
    "whoAsked": "શરેવણી કોણે માંગેલી અથવા લીધેલી?",
    "centralEmployee": "કેન્દ્ર સરકાર કર્મચારી / PSU / બેંક",
    "stateEmployee": "રાજ્ય સરકાર અથવા સ્થાનિક સંસ્થા કર્મચારી",
    "policeVigilance": "પોલીસ અથવા જાગૃતતા કર્મચારી",
    "onlineDemand": "ઓનલાઇન / ફોન / UPI માંગ",
    "notSure": "નિશ્ચિત નથી",
    "officialName": "અધિકારી નું નામ (જાણી હોય તો)",
    "officialNamePlaceholder": "ઉદાહરણ: Ramesh Verma",
    "designation": "હોદ્દો",
    "designationPlaceholder": "ઉદાહરણ: Clerk, Inspector",
    "departmentOffice": "વિભાગ / કાર્યાલય",
    "departmentPlaceholder": "ઉદાહરણ: Regional Passport Office",
    "officeAddress": "કાર્યાલય સરનામું / વિસ્તાર",
    "officeAddressPlaceholder": "જમાવટ, માર્ગ, શહેર અથવા જિલ્લા",
    "serviceWork": "કોઈ સેવા અથવા કાર્ય જોડાયેલું હતું?",
    "servicePlaceholder": "ઉદાહરણ: Building permit, licence renewal, pension file",
    "whatDemanded": "શું માંગીવાયું",
    "amountPaid": "કિંમત માંગી/પુરી ચૂકવેલી (₹)",
    "amountPlaceholder": "ઉદાહરણ: 2000",
    "paymentForm": "ચુકવણીનું પ્રકાર",
    "cash": "નગદ",
    "upi": "UPI / ઓનલાઈન ટ્રાન્સફર",
    "bankTransfer": "બેંક ટ્રાન્સફર",
    "giftGoods": "ઉપહાર અથવા સામાન",
    "favourBenefit": "પસંદગી અથવા અન્ય લાભ",
    "demandMaker": "માગ કોણે કર્યું?",
    "officialPersonally": "અધિકારી પોતે",
    "intermediary": "મધ્યસ્થ / એજન્ટ / દલાલ",
    "both": "બન્ને",
    "witnessDetails": "ગવાહ / મધ્યસ્થ વિગતો",
    "witnessPlaceholder": "નામ અને સંપર્ક, જો હોય તો",
    "dateDemand": "માગની તારીખ",
    "timeApprox": "સમય (અંદાજે)",
    "placeDemand": "માગ ક્યાં કરવામાં આવી",
    "placePlaceholder": "ઉદાહરણ: કાઉન્ટર 4, ઓફિસ ગેટ, ફોન પર",
    "factsLabel": "અધિકારીએ શું કહ્યું અથવા કર્યું (ફક્ત તથ્ય)",
    "factsPlaceholder": "યથાર્થ રીતે શું કહ્યું અથવા કર્યું તેનું ક્રમવાર વર્ણન કરો.",
    "evidenceLabel": "સાક્ષ્ય અને સંદર્ભ વિગતો",
    "evidencePlaceholder": "સંદેશ, ફોન નંબર, ઈમેલ, નોટિસ, રસીદ, સ્ક્રીનશોટ અથવા ટ્રાન્ઝેક્શન વિગતો",
    "referenceLabel": "અરજી / ફાઇલ / લાઇસન્સ સંદર્ભ નંબર",
    "referencePlaceholder": "ઉદાહરણ: Application No. 12345/2026",
    "finalReview": "અંતિમ સમીક્ષા",
    "analysing": "વિશ્લેષણ કરી રહ્યા છે…",
    "exactWebsite": "અનુસાર ચોક્કસ વેબસાઇટ શોધો",
    "runAssistant": "સબમિટ કરતા પહેલા AI સહાયક ચલાવો",
    "submitComplaint": "શિકાયત સબમિટ કરો",
    "continue": "ચાલુ રાખો",
    "back": "પાછું",
    "securityCheck": "સિક્યુરિટી ચેક: 7 + 4 દાખલ કરો",
    "successRedirect": "તમારી ફરિયાદ રેકોર્ડ કરી લેવામાં આવી છે। ખરેખર સત્તાવાર ગંતવ્ય ખોલી રહ્યું છે…",
    "openOfficial": "ખાસ સત્તાવાર વેબસાઇટ ખોલો",
    "seeOfficer": "ઉપર દર્શાવેલો અધિકારી જુઓ",
    "officialDestination": "સાચો સત્તાવાર ગંતવ્ય પસંદ કરો",
    "education": "શિક્ષણ",
    "backPortal": "પોર્ટલ પર પાછા જાઓ",
    "useGuide": "આને માર્ગદર્શિકા તરીકે ઉપયોગ કરો",
    "safetyReminder": "સુરક્ષા યાદ અપાવવી"
  },
  "hi": {
    "fullName": "पूर्ण नाम",
    "yourFullName": "आपका पूरा नाम",
    "mobileNumber": "मोबाइल नंबर",
    "tenDigitMobile": "10‑अंकों का मोबाइल",
    "emailOptional": "ईमेल (वैकल्पिक)",
    "emailPlaceholder": "you@example.com",
    "addressCityOptional": "पता / शहर (वैकल्पिक)",
    "whereAgenciesReach": "कहाँ से एजेंसियाँ आप तक पहुँच सकती हैं",
    "idType": "पहचान प्रकार",
    "voterId": "मतदाता पहचान पत्र",
    "pan": "PAN",
    "drivingLicence": "ड्राइविंग लाइसेंस",
    "idNumber": "पहचान संख्या",
    "enterIdNumber": "पहचान संख्या दर्ज करें",
    "oneTimePassword": "वन‑टाइम पासवर्ड",
    "otpPlaceholder": "6‑अंकों का OTP",
    "sending": "भेजा जा रहा…",
    "sendOtp": "OTP भेजें",
    "checking": "जाँच की जा रही है…",
    "verifyOtp": "OTP सत्यापित करें",
    "phoneVerified": "फ़ोन सत्यापित हो गया",
    "reportAnonymously": "गुमनाम रूप से रिपोर्ट करें",
    "noIdentityRequired": "नाम, फोन या पहचान की आवश्यकता नहीं। आपको एक ट्रैकिंग आईडी मिलेगी।",
    "select": "चुनें",
    "whoAsked": "किसने रिश्वत माँगी या ली?",
    "centralEmployee": "केन्द्रीय सरकार का कर्मचारी / PSU / बैंक",
    "stateEmployee": "राज्य सरकार या स्थानीय निकाय का कर्मचारी",
    "policeVigilance": "पुलिस या सतर्कता कर्मी",
    "onlineDemand": "ऑनलाइन / फोन / UPI माँग",
    "notSure": "पक्का नहीं",
    "officialName": "अधिकारी का नाम (यदि ज्ञात हो)",
    "officialNamePlaceholder": "उदा. Ramesh Verma",
    "designation": "पदनाम",
    "designationPlaceholder": "उदा. क्लर्क, निरीक्षक",
    "departmentOffice": "विभाग / कार्यालय",
    "departmentPlaceholder": "उदा. क्षेत्रीय पासपोर्ट कार्यालय",
    "officeAddress": "कार्यालय का पता / क्षेत्र",
    "officeAddressPlaceholder": "भवन, सड़क, शहर या जिला",
    "serviceWork": "किस सेवा या कार्य का संबंध था?",
    "servicePlaceholder": "उदा. भवन परमिट, लाइसेंस नवीनीकरण, पेंशन फाइल",
    "whatDemanded": "क्या माँगा गया था",
    "amountPaid": "माँगी / दी गयी राशि (₹)",
    "amountPlaceholder": "उदा. 2000",
    "paymentForm": "भुगतान का रूप",
    "cash": "नकद",
    "upi": "UPI / ऑनलाइन ट्रांसफर",
    "bankTransfer": "बैंक ट्रांसफर",
    "giftGoods": "उपहार या सामान",
    "favourBenefit": "स्रोत या अन्य लाभ",
    "demandMaker": "माँग किसने की?",
    "officialPersonally": "अधिकारी ने स्वयं",
    "intermediary": "मध्यस्थ / एजेंट / दलाल",
    "both": "दोनों",
    "witnessDetails": "गवाहों / मध्यस्थ का विवरण",
    "witnessPlaceholder": "नाम और संपर्क, यदि कोई हों",
    "dateDemand": "माँग की तिथि",
    "timeApprox": "समय (अनुमानित)",
    "placeDemand": "जहाँ माँग की गई थी",
    "placePlaceholder": "उदा. काउंटर 4, कार्यालय का द्वार, फोन पर",
    "factsLabel": "अधिकारी ने क्या कहा या किया (केवल तथ्य)",
    "factsPlaceholder": "ठीक‑ठीक बतायें कि क्या कहा या किया गया, क्रम में।",
    "evidenceLabel": "सबूत और संदर्भ विवरण",
    "evidencePlaceholder": "संदेश, फोन नंबर, ईमेल, नोटिस, रसीदें, स्क्रीनशॉट या लेन‑देन विवरण",
    "referenceLabel": "आवेदन / फ़ाइल / लाइसेंस संदर्भ संख्या",
    "referencePlaceholder": "उदा. आवेदन सं. 12345/2026",
    "finalReview": "अंतिम समीक्षा",
    "analysing": "विश्लेषण किया जा रहा है…",
    "exactWebsite": "सटीक वेबसाइट खोजें",
    "runAssistant": "जमा करने से पहले AI सहायक चलाएँ",
    "submitComplaint": "शिकायत जमा करें",
    "continue": "जारी रखें",
    "back": "वापस",
    "securityCheck": "सुरक्षा जांच: 7 + 4 दर्ज करें",
    "successRedirect": "आपकी शिकायत दर्ज कर दी गई है। सटीक आधिकारिक गंतव्य खोला जा रहा है…",
    "openOfficial": "सटीक आधिकारिक वेबसाइट खोलें",
    "seeOfficer": "ऊपर दिए अधिकारी को देखें",
    "officialDestination": "सही आधिकारिक गंतव्य चुनें",
    "education": "शिक्षा",
    "backPortal": "पोर्टल पर वापस",
    "useGuide": "इसे मार्गदर्शिका के रूप में उपयोग करें",
    "safetyReminder": "सुरक्षा स्मरण"
  },
  "kn": {
    "fullName": "ಸರಿಯಾದ ಹೆಸರು",
    "yourFullName": "ನಿಮ್ಮ ಸಂಪೂರ್ಣ ಹೆಸರು",
    "mobileNumber": "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    "tenDigitMobile": "10 ಅಂಕಿಯ ಮೊಬೈಲ್",
    "emailOptional": "ಇಮೇಲ್ (ಐಚ್ಛಿಕ)",
    "emailPlaceholder": "you@example.com",
    "addressCityOptional": "ವಿಳಾಸ / ನಗರ (ಐಚ್ಛಿಕ)",
    "whereAgenciesReach": "ಏಜೆನ್ಸಿಗಳು ನಿಮಗೆ ಎಲ್ಲಿ ತಲುಪಬಹುದು",
    "idType": "ಐಡಿ ವಿಧ",
    "voterId": "ಚುನಾವಣಾಧಿಕಾರಿ ಐಡಿ",
    "pan": "PAN",
    "drivingLicence": "ಡ್ರೈವಿಂಗ್ ಲೈಸೆನ್ಸ್",
    "idNumber": "ಐಡಿ ಸಂಖ್ಯೆ",
    "enterIdNumber": "ಐಡಿ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ",
    "oneTimePassword": "ಒಂದು ಬಾರಿ ಪಾಸ್ವರ್ಡ್",
    "otpPlaceholder": "6 ಅಂಕಿಯ OTP",
    "sending": "ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ…",
    "sendOtp": "OTP ಕಳುಹಿಸಿ",
    "checking": "ಪರಿಶೀಲನೆ…",
    "verifyOtp": "OTP ಪರಿಶೀಲಿಸಿ",
    "phoneVerified": "ಫೋನ್ ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
    "reportAnonymously": "ನಾಮವಾಚಕವಾಗಿ ವರದಿ ಮಾಡಿ",
    "noIdentityRequired": "ಹೆಸರು, ಫೋನ್ ಅಥವಾ ಐಡಿಗೆ ಅಗತ್ಯವಿಲ್ಲ. ನಿಮಗೆ ಟ್ರ್ಯಾಕಿಂಗ್ ಐಡಿ ಸಿಗಲಿದೆ.",
    "select": "ಆಯ್ಕೆಮಾಡಿ",
    "whoAsked": "ಹಣದ ಬೇಡಿಕೆಯನ್ನು ಯಾರು ಮಾಡಿದರು ಅಥವಾ ಪಡೆದರು?",
    "centralEmployee": "ಕೇಂದ್ರ ಸರ್ಕಾರದ ಉದ್ಯೋಗಿ / PSU / ಬ್ಯಾಂಕ್",
    "stateEmployee": "ರಾಜ್ಯ ಸರ್ಕಾರ ಅಥವಾ ಸ್ಥಳೀಯ ಸಂಸ್ಥೆಯ ಉದ್ಯೋಗಿ",
    "policeVigilance": "ಹೆದ್ದಾರಿ ಅಥವಾ ಜಾಗೃತಿ ಸಿಬ್ಬಂದಿ",
    "onlineDemand": "ಆನ್‌ಲೈನ್ / ಫೋನ್ / UPI ಬೇಡಿಕೆ",
    "notSure": "ಖಚಿತವಿಲ್ಲ",
    "officialName": "ಅಧಿಕಾರಿಯ ಹೆಸರು (ಗೋಚರಿಸದಿದ್ದರೆ)",
    "officialNamePlaceholder": "ಉದಾ. Ramesh Verma",
    "designation": "ಹುದ್ದೆ",
    "designationPlaceholder": "ಉದಾ. ಕ್ಲರ್ಕ್, ಇನ್ಸ್‌ಪೆಕ್ಟರ್",
    "departmentOffice": "ವಿಭಾಗ / ಕಚೇರಿ",
    "departmentPlaceholder": "ಉದಾ. ಪ್ರಾದೇಶಿಕ ಪಾಸ್‌ಪೋರ್ಟ್ ಕಚೇರಿ",
    "officeAddress": "ಕಾರ्यालय ವಿಳಾಸ / ಪ್ರದೇಶ",
    "officeAddressPlaceholder": "ಭವನ, ರಸ್ತೆ, ನಗರ ಅಥವಾ ಜಿಲ್ಲೆ",
    "serviceWork": "ಯಾವ ಸೇವೆ ಅಥವಾ ಕೆಲಸ ಸಂಬಂದಿತವಿತ್ತು?",
    "servicePlaceholder": "ಉದಾ. ಕಟ್ಟಡ ಅನುಮತಿ, ಲೈಸೆನ್ಸ್ ನವೀಕರಣ, ಪಿಂಚಣಿ ಫೈಲ್",
    "whatDemanded": "ಏನು ಬೇಡப்பட்டது",
    "amountPaid": "ಬೇಡಿಕೆಯಾಗಿದ/ಕೊಟ್ಟ сумма (₹)",
    "amountPlaceholder": "ಉದಾ. 2000",
    "paymentForm": "ಪಾವತಿ ರೀತಿಯ",
    "cash": "ನಗದು",
    "upi": "UPI / ಆನ್‌ಲೈನ್ ವರ್ಗಾವಣೆ",
    "bankTransfer": "ಬ್ಯಾಂಕ್ ವರ್ಗಾವಣೆ",
    "giftGoods": "ಉಡುಗೆ ಅಥವಾ ಸರಕು",
    "favourBenefit": "ಆನಂದ ಅಥವಾ ಇತರ ಲಾಭ",
    "demandMaker": "ಬೇಡಿಕೆಯನ್ನು ಯಾರು ಮಾಡಿದರು?",
    "officialPersonally": "ಅಧಿಕಾರಿ ವೈಯಕ್ತಿಕವಾಗಿ",
    "intermediary": "ಮಧ್ಯವರ್ತಿ / ಏಜೆಂಟ್ / ಮಧ್ಯಸ್ಥ",
    "both": "ಎರಡೂ",
    "witnessDetails": "ಸಾಕ್ಷಿಗಳು / ಮಧ್ಯವರ್ತಿಯ ವಿವರಗಳು",
    "witnessPlaceholder": "ಹೆಸರುಗಳು ಮತ್ತು ಸಂಪರ್ಕ, ಇದ್ದರೆ",
    "dateDemand": "ಬೇಡಿಕೆಯ ದಿನಾಂಕ",
    "timeApprox": "ಸಮಯ (ಅಂದಾಜು)",
    "placeDemand": "ಬೇಡಿಕೆ ಮಾಡಲಾದ ಸ್ಥಳ",
    "placePlaceholder": "ಉದಾ. ಕೌಂಟರ್ 4, ಕಚೇರಿ ಗೇಟ್, ಫೋನ್‌ನಲ್ಲಿ",
    "factsLabel": "ಅಧಿಕಾರಿ ಏನು ಹೇಳಿದರು ಅಥವಾ ಮಾಡಿದ್ದಾರೆ (ಕೆವಲ ವಿಚಾರಗಳು)",
    "factsPlaceholder": "ನಿಖರವಾಗಿ ಏನು ಹೇಳಲಾಯಿತು ಅಥವಾ ಮಾಡಲಾಯಿತು, ಕ್ರಮವಾಗಿ ವಿವರಿಸಿ.",
    "evidenceLabel": "ಸಾಕ್ಷ್ಯಗಳು ಮತ್ತು ಉಲ್ಲೇಖ ವಿವರಗಳು",
    "evidencePlaceholder": "ಸಂದೇಶಗಳು, ದೂರವಾಣಿ ನಂಬರು, ಇಮೇಲ್‌ಗಳು, ಸೂಚನೆಗಳು, ರಸಿದುಗಳು, ಸ್ಕ್ರೀನ್‌ಶಾಟ್‌ಗಳು ಅಥವಾ ಲೆನ‑ದೇವನ ಮಾಹಿತಿಗಳು",
    "referenceLabel": "ಅರ್ಜಿಯ / ಫೈಲ್ / ಲೈಸೆನ್ಸ್ ಉಲ್ಲೇಖ ಸಂಖ್ಯೆ",
    "referencePlaceholder": "ಉದಾ. ಅರ್ಜಿ ಸಂ. 12345/2026",
    "finalReview": "ಅಂತಿಮ ಪುನರ್‌ವಿಮರ್ಶೆ",
    "analysing": "ವಿಶ್ಲೇಷಣೆ ಮಾಡಲಾಗುತ್ತಿದೆ…",
    "exactWebsite": "ನಿಖರ ವೆಬ್‌ಸೈಟ್ ಕಂಡುಹಿಡಿ",
    "runAssistant": "ಸಲ್ಲಿಸುವ ಮೊದಲು AI ಸಹಾಯಕರನ್ನು ಚಾಲನೆ ಮಾಡಿ",
    "submitComplaint": "ದೂರು ಸಲ್ಲಿಸಿ",
    "continue": "ಮುಂದುವರಿಸಿ",
    "back": "ಹಿಂದಿಗೆ",
    "securityCheck": "ಸುರಕ್ಷತೆ ಪರಿಶೀಲನೆ: 7 + 4 ನಮೂದಿಸಿ",
    "successRedirect": "ನಿಮ್ಮ ದೂರು ದಾಖಲಾಗಿರುವುದು. ನಿಖರ ಅಧಿಕೃತ ಗಮ್ಯಸ್ಥಾನ ತೆರೆಯಲಾಗುತ್ತಿದೆ…",
    "openOfficial": "ನಿಖರ ಅಧಿಕೃತ ವೆಬ್‌ಸೈಟ್ ತೆರೆಯಿರಿ",
    "seeOfficer": "ಮೇಲಿನ ಅಧಿಕಾರಿಯನ್ನು ನೋಡಿ",
    "officialDestination": "ಸರಿಯಾದ ಅಧಿಕೃತ ಗಮ್ಯಸ್ಥಾನ ಆಯ್ಕೆಮಾಡಿ",
    "education": "ಶಿಕ್ಷಣ",
    "backPortal": "ಪೋರ್ಟಲ್‌ಗೆ ಹಿಂದಿರುಗಿ",
    "useGuide": "ಇದನ್ನು ಮಾರ್ಗದರ್ಶಿಯಾಗಿ ಬಳಸಿ",
    "safetyReminder": "ಬೇಲೆಯ ಸೂಚನೆ"
  },
  "ks": {
    "fullName": "پورا نام",
    "yourFullName": "توہند پورا نام",
    "mobileNumber": "موبائل نمبر",
    "tenDigitMobile": "10 ہند نمر موبائل",
    "emailOptional": "ایمیل (اختیاری)",
    "emailPlaceholder": "you@example.com",
    "addressCityOptional": "پتہ / شہر (اختیاری)",
    "whereAgenciesReach": "ایجنسیاں تہند کن یتھ پہنچان",
    "idType": "شناخت قسم",
    "voterId": "وٹر آئی ڈی",
    "pan": "PAN",
    "drivingLicence": "ڈرائیونگ لائسنس",
    "idNumber": "شناخت نمبر",
    "enterIdNumber": "شناخت نمبر درج کرۍ",
    "oneTimePassword": "ایک وقتی پاس ورڈ",
    "otpPlaceholder": "6 ہند عدد OTP",
    "sending": "بھیجٕ رہہ…",
    "sendOtp": "OTP بھیژ",
    "checking": "چیک کرٕ…",
    "verifyOtp": "OTP تصدیق کرٕ",
    "phoneVerified": "فون تصدیق چھہ",
    "reportAnonymously": "نامعلوم طور پر رپورٹ کرن",
    "noIdentityRequired": "نام، فون یا شناخت ضروری نہٕ۔ تندک ٹریکنگ آئی ڈی ملان",
    "select": "منتخب کرن",
    "whoAsked": "کُنٛسٛن رشوت مانگۍ یا لیۍ؟",
    "centralEmployee": "مرکزی حکومت ملازم / PSU / بینک",
    "stateEmployee": "ریاستی حکومت یا مقامی ادارہ ملازم",
    "policeVigilance": "پولیس یا ویجلنس عملہ",
    "onlineDemand": "آن لائن / فون / UPI مانگ",
    "notSure": "شُبہ دار",
    "officialName": "آفیشل ہند نام (اگر معلوم ہو)",
    "officialNamePlaceholder": "مثلاً Ramesh Verma",
    "designation": "عہدہ",
    "designationPlaceholder": "مثلاً کلرک، انسپکٹر",
    "departmentOffice": "محکمہ / دفتر",
    "departmentPlaceholder": "مثلاً ریجنل پاسپورٹ آفس",
    "officeAddress": "دفتر پتہ / علاقہ",
    "officeAddressPlaceholder": "بلڈنگ، سڑک، شہر یا ضلع",
    "serviceWork": "کس خدمت یا کام سے متعلق؟",
    "servicePlaceholder": "مثلاً بلڈنگ پرمٹ، لائسنس تجدید، پنشن فائل",
    "whatDemanded": "کیا مانگا گیا",
    "amountPaid": "مانگی/دی گئی رقم (₹)",
    "amountPlaceholder": "مثلاً 2000",
    "paymentForm": "ادائیگی کی شکل",
    "cash": "نقد",
    "upi": "UPI / آن لائن ٹرانسفر",
    "bankTransfer": "بینک ٹرانسفر",
    "giftGoods": "تحفہ یا سامان",
    "favourBenefit": "سہولت یا دیگر فائدہ",
    "demandMaker": "مانگ کس نے کی؟",
    "officialPersonally": "آفیشل نے ذاتی طور پر",
    "intermediary": "درمیان کار / ایجنٹ / ثالث",
    "both": "دونوں",
    "witnessDetails": "گواہ/درمیان کار کی تفصیلات",
    "witnessPlaceholder": "نام اور رابطہ، اگر ہوں",
    "dateDemand": "مانگ کی تاریخ",
    "timeApprox": "وقت (تقریباً)",
    "placeDemand": "جہاں مانگ کی گئی",
    "placePlaceholder": "مثلاً کاؤنٹر 4، دفتر کے دروازے، فون پر",
    "factsLabel": "آفیشل نے کیا کہا یا کیا (صرف حقائق)",
    "factsPlaceholder": "بالکل بتائیں کیا کہا یا کیا گیا، ترتیب سے۔",
    "evidenceLabel": "شواہد اور حوالہ کی تفصیلات",
    "evidencePlaceholder": "پیغامات، فون نمبر، ای میلز، نوٹس، رسیدیں، اسکرین شاٹس یا لین دین کی تفصیلات",
    "referenceLabel": "درخواست / فائل / لائسنس حوالہ نمبر",
    "referencePlaceholder": "مثلاً درخواست نمبر 12345/2026",
    "finalReview": "حتمی جائزہ",
    "analysing": "تجزیہ کیا جا رہا ہے…",
    "exactWebsite": "بالغ ویب سائٹ تلاش کریں",
    "runAssistant": "جمع کرانے سے پہلے AI معاون چلائیں",
    "submitComplaint": "شکایت جمع کریں",
    "continue": "جاری رکھیں",
    "back": "واپس",
    "securityCheck": "سیکیورٹی چیک: 7 + 4 درج کریں",
    "successRedirect": "آپ کی شکایت درج کر لی گئی ہے۔ بالکل سرکاری منزل کھولی جا رہی ہے…",
    "openOfficial": "بالکل سرکاری ویب سائٹ کھولیں",
    "seeOfficer": "اوپر والا افسر دیکھیں",
    "officialDestination": "صحیح سرکاری منزل منتخب کریں",
    "education": "تعلیم",
    "backPortal": "پورٹل پر واپس",
    "useGuide": "اسے رہنما کے طور پر استعمال کریں",
    "safetyReminder": "حفاظتی یاددہانی"
  },
  "kok": {
    "fullName": "संपूर्ण नाव",
    "yourFullName": "तुमचें संपूर्ण नाव",
    "mobileNumber": "मोबाइल नंबर",
    "tenDigitMobile": "10 अंकांचो मोबाइल",
    "emailOptional": "ईमेल (पर्यायी)",
    "emailPlaceholder": "you@example.com",
    "addressCityOptional": "पत्ता / शहर (पर्यायी)",
    "whereAgenciesReach": "एजन्सी कितें तुमका पोहचुं शकतात",
    "idType": "ओळख प्रकार",
    "voterId": "मतदार ओळखपत्र",
    "pan": "PAN",
    "drivingLicence": "ड्रायविंग परवाना",
    "idNumber": "ओळख क्रमांक",
    "enterIdNumber": "ओळख क्रमांक टाका",
    "oneTimePassword": "वन‑टाईम पासवर्ड",
    "otpPlaceholder": "6 अंकांचो OTP",
    "sending": "पठोप जातां…",
    "sendOtp": "OTP पाठवा",
    "checking": "तपासोता आसा…",
    "verifyOtp": "OTP पडताळा",
    "phoneVerified": "फोन पडताळलें",
    "reportAnonymously": "नामविहीन पद्धतीन रिपोर्ट करा",
    "noIdentityRequired": "नाव, फोन वा ओळख आवश्यक नाय. तुमका ट्रॅकिंग आयडी मिळोया.",
    "select": "निवडा",
    "whoAsked": "कोणाचेन फज्जत/रिश्वतका माग केली आनी घेतली?",
    "centralEmployee": "केंद्रीय सरकारचो कर्मचारी / PSU / बँक",
    "stateEmployee": "राज्य सरकार वा स्थानिक संस्था कर्मचारी",
    "policeVigilance": "पोलीस वा चौकशी कर्मचारी",
    "onlineDemand": "ऑनलाइन / फोन / UPI माग",
    "notSure": "नक्को नाय",
    "officialName": "अधिकाऱ्याचें नाव (जर कळता)",
    "officialNamePlaceholder": "उदा. Ramesh Verma",
    "designation": "पद",
    "designationPlaceholder": "उदा. Clerk, Inspector",
    "departmentOffice": "विभाग / कार्यालय",
    "departmentPlaceholder": "उदा. Regional Passport Office",
    "officeAddress": "कार्यालय पत्ता / भाग",
    "officeAddressPlaceholder": "बिल्डिंग, रस्ता, शहर वा जिल्हो",
    "serviceWork": "कोणत्या सेवेक किंवा कामाक संबंध आसा?",
    "servicePlaceholder": "उदा. Building permit, licence renewal, pension file",
    "whatDemanded": "काय मागितलें",
    "amountPaid": "मागितलें / दिलें रक्कम (₹)",
    "amountPlaceholder": "उदा. 2000",
    "paymentForm": "देण्याचो प्रकार",
    "cash": "रोख",
    "upi": "UPI / ऑनलाइन ट्रान्सफर",
    "bankTransfer": "बँक ट्रान्सफर",
    "giftGoods": "भेट वा सामान",
    "favourBenefit": "पकड किंवा इतर फायदा",
    "demandMaker": "मागणी कोण केलय?",
    "officialPersonally": "अधिकारी स्वतःनी",
    "intermediary": "मध्यस्थ / एजन्ट / मध्येमाणूस",
    "both": "दोन्ही",
    "witnessDetails": "साक्षीदार / मध्यस्थाचें तपशील",
    "witnessPlaceholder": "नाव आनी संपर्क, जरी आसा",
    "dateDemand": "मागणीची तारीख",
    "timeApprox": "वेळ (अंदाजे)",
    "placeDemand": "मागणी जिथें केली तशी जागा",
    "placePlaceholder": "उदा. काउंटर 4, कार्यालय दरवाजो, फोन वर",
    "factsLabel": "अधिकाऱ्यांनी काय म्हटलें किंवा केलें (फक्त घटक)",
    "factsPlaceholder": "ठीक तशें सांगा काय म्हटलें वा केलें, क्रमानुसार.",
    "evidenceLabel": "पुरावे आनी संदर्भ तपशील",
    "evidencePlaceholder": "मेसेजेस, फोन नंबर, ईमेल्स, नोटिसेस, पावत्या, स्क्रीनशॉट वा व्यवहार तपशील",
    "referenceLabel": "अर्ज / फाईल / परवाना संदर्भ क्रमांक",
    "referencePlaceholder": "उदा. Application No. 12345/2026",
    "finalReview": "अंतिम पुनरावलोकन",
    "analysing": "विश्लेषण केलं जातां…",
    "exactWebsite": "बरोबर वेबसाइट शोधा",
    "runAssistant": "सबमिट करण्याआधी AI सहाय्यक चालवा",
    "submitComplaint": "तक्रार सादर करा",
    "continue": "सुरू ठेवा",
    "back": "मागें",
    "securityCheck": "सुरक्षा तपासणी: 7 + 4 टाका",
    "successRedirect": "तुमची तक्रार नोंदवली गेली आसा. बरोबर अधिकृत गंतव्य उघडतां…",
    "openOfficial": "बरोबर अधिकृत वेबसाइट उघडा",
    "seeOfficer": "वरिल अधिकारी पाहा",
    "officialDestination": "योग्य अधिकृत गंतव्य निवडा",
    "education": "शिक्षण",
    "backPortal": "पोर्टलक परत जा",
    "useGuide": "ह्याला मार्गदर्शक म्हणून वापरा",
    "safetyReminder": "सुरक्षेची आठवण"
  },
  "mai": {
    "fullName": "पूरा नाम",
    "yourFullName": "अहाँक पूरा नाम",
    "mobileNumber": "मोबाइल नंबर",
    "tenDigitMobile": "10 अंकक मोबाइल",
    "emailOptional": "ईमेल (वैकल्पिक)",
    "emailPlaceholder": "you@example.com",
    "addressCityOptional": "ठिकाना / शहर (वैकल्पिक)",
    "whereAgenciesReach": "कहाँ सऽ एजेंसी सभ अहाँ तक पहुँच सकै छथि",
    "idType": "पहिचान प्रकार",
    "voterId": "मतदाता पहचान पत्र",
    "pan": "PAN",
    "drivingLicence": "ड्राइविंग लाइसेंस",
    "idNumber": "पहिचान संख्या",
    "enterIdNumber": "पहिचान संख्या प्रविष्ट करी",
    "oneTimePassword": "वन‑टाइम पासवर्ड",
    "otpPlaceholder": "6‑अंकीय OTP",
    "sending": "भेजल जा रहल अछि…",
    "sendOtp": "OTP भेजू",
    "checking": "जाँच भऽ रहल अछि…",
    "verifyOtp": "OTP सत्यापित करी",
    "phoneVerified": "फोन सत्यापित भऽ गेल",
    "reportAnonymously": "नाम छुपाक रिपोर्ट करू",
    "noIdentityRequired": "नाम, फोन वा आईडी आवश्यक नहि। अहाँ केँ एक ट्रैकिंग आईडी भेटत।",
    "select": "चुनू",
    "whoAsked": "के रिश्वत मांगलक वा लेलक?",
    "centralEmployee": "केंद्र सरकारक कर्मचारी / PSU / बैंक",
    "stateEmployee": "राज्य सरकार वा स्थानीय निकायक कर्मचारी",
    "policeVigilance": "पुलिस वा सतर्कता कर्मी",
    "onlineDemand": "ऑनलाइन / फोन / UPI माँग",
    "notSure": "पक्का नहि",
    "officialName": "अधिकारीक नाम (यदि ज्ञात हो)",
    "officialNamePlaceholder": "उदा. Ramesh Verma",
    "designation": "पदनाम",
    "designationPlaceholder": "उदा. Clerk, Inspector",
    "departmentOffice": "विभाग / कार्यालय",
    "departmentPlaceholder": "उदा. Regional Passport Office",
    "officeAddress": "कार्यालयक पता / क्षेत्र",
    "officeAddressPlaceholder": "भवन, सड़क, शहर वा जिला",
    "serviceWork": "कतेक सेवा वा काज शामिल छल?",
    "servicePlaceholder": "उदा. Building permit, licence renewal, pension file",
    "whatDemanded": "की माँगल गेल",
    "amountPaid": "माँगल/देल गेल राशि (₹)",
    "amountPlaceholder": "उदा. 2000",
    "paymentForm": "भुगतानक रूप",
    "cash": "नकद",
    "upi": "UPI / ऑनलाइन ट्रांसफर",
    "bankTransfer": "बैंक ट्रांसफर",
    "giftGoods": "उपहार वा सामान",
    "favourBenefit": "अनुग्रह वा अन्य लाभ",
    "demandMaker": "माँग केलक के?",
    "officialPersonally": "अधिकारी स्वयं",
    "intermediary": "मध्यस्थ / एजेंट / दलाल",
    "both": "दूनु",
    "witnessDetails": "साक्षीक/मध्यस्थक विवरण",
    "witnessPlaceholder": "नाम आ संपर्क, यदि कोनो हो",
    "dateDemand": "माँगक तिथि",
    "timeApprox": "समय (अनुमानित)",
    "placeDemand": "माँग जतय भेल",
    "placePlaceholder": "उदा. काउंटर 4, कार्यालयक प्रवेशद्वार, फोन पर",
    "factsLabel": "अधिकारी की कहलथिन वा केलथिन (केवल तथ्य)",
    "factsPlaceholder": "ठीक‑ठीक वर्णन करू कि की कहल गेल वा केल गेल, क्रमशः।",
    "evidenceLabel": "साक्ष्य आ संदर्भ विवरण",
    "evidencePlaceholder": "संदेश, फोन नंबर, ईमेल, नोटिस, रसीद, स्क्रीनशॉट वा लेन‑देन विवरण",
    "referenceLabel": "आवेदन / फाइल / लाइसेंस संदर्भ संख्या",
    "referencePlaceholder": "उदा. Application No. 12345/2026",
    "finalReview": "अंतिम समीक्षा",
    "analysing": "विश्लेषण भऽ रहल अछि…",
    "exactWebsite": "सटीक वेबसाइट खोजू",
    "runAssistant": "जमा करऽ सऽ पहिने AI सहायक चलाऊ",
    "submitComplaint": "शिकायत जमा करू",
    "continue": "जारी राखू",
    "back": "वापस",
    "securityCheck": "सुरक्षा जांच: 7 + 4 दर्ज करू",
    "successRedirect": "अहाँक शिकायत दर्ज भऽ गेल। सटीक आधिकारिक गंतव्य खोलल जा रहल अछि…",
    "openOfficial": "सटीक आधिकारिक वेबसाइट खोलू",
    "seeOfficer": "ऊपरक अधिकारी देखू",
    "officialDestination": "सही आधिकारिक गंतव्य चुनू",
    "education": "शिक्षा",
    "backPortal": "पोर्टलक दिस लग लौटू",
    "useGuide": "एक दिशानिर्देशक क रूप मे उपयोग करू",
    "safetyReminder": "सुरक्षा संबंधी स्मरण"
  },
  "ml": {
    "fullName": "പൂർണ്ണ നാമം",
    "yourFullName": "നിങ്ങളുടെ പൂർണ്ണ നാമം",
    "mobileNumber": "മൊബൈൽ നമ്പർ",
    "tenDigitMobile": "10‑അസംഖ്യ മൊബൈൽ",
    "emailOptional": "ഇമെയിൽ (ഐച്ഛികം)",
    "emailPlaceholder": "you@example.com",
    "addressCityOptional": "വിലാസം / നഗരം (ഐച്ഛികം)",
    "whereAgenciesReach": " ഏജൻസികൾ നിങ്ങളെ എവിടെ എത്തിച്ചേരാൻ കഴിയും",
    "idType": "ഐഡി തരം",
    "voterId": "വോട്ടർ ഐഡി",
    "pan": "PAN",
    "drivingLicence": "ഡ്രൈവിംഗ് ലൈസൻസ്",
    "idNumber": "ഐഡി നമ്പർ",
    "enterIdNumber": "ഐഡി നമ്പർ നൽകുക",
    "oneTimePassword": "ഒറോൺടൈം പാസ്‌വേഡ്",
    "otpPlaceholder": "6‑അസംഖ്യ OTP",
    "sending": "അയയ്ക്കുന്നു…",
    "sendOtp": "OTP അയക്കുക",
    "checking": "പരിശോധിക്കുന്നു…",
    "verifyOtp": "OTP സ്ഥിരീകരിക്കുക",
    "phoneVerified": "ഫോൺ സ്ഥിരീകരിച്ചു",
    "reportAnonymously": "വെളിപ്പെടുത്താതെയായി റിപ്പോർട്ട് ചെയ്യുക",
    "noIdentityRequired": "പേര്, ഫോൺ അല്ലെങ്കിൽ ഐഡി ആവശ്യമായിട്ടില്ല. നിങ്ങളെൊരു ട്രാക്കിംഗ് ഐഡി ലഭിക്കും.",
    "select": "തിരഞ്ഞെടുക്കുക",
    "whoAsked": "ആശ്ചര്യപ്പെട്ടതു– रिश्वत ആരാണ് ചോദിച്ചത്/എടുത്തത്?",
    "centralEmployee": "കേന്ദ്ര സർക്കാരിലെ ഉദ്യോഗസ്ഥൻ / PSU / ബാങ്ക്",
    "stateEmployee": "സംസ്ഥാനം സംസ്ഥാന സർക്കാർ അല്ലെങ്കിൽ പ്രാദേശിക സ്ഥാപന ജോലിക്കാരി",
    "policeVigilance": "പോലീസ് അല്ലെങ്കിൽ വാചാലതാ ജീവനക്കാർ",
    "onlineDemand": "ഓൺലൈൻ / ഫോൺ / UPI ആവശ്യപ്പെടൽ",
    "notSure": "നിശ്ചിതമല്ല",
    "officialName": "അധികാരിയുടെ പേര് (അറിയാമെങ്കിൽ)",
    "officialNamePlaceholder": "ഉദാ. Ramesh Verma",
    "designation": "ഏഴ്‌designation",
    "designationPlaceholder": "ഉദാ. Clerk, Inspector",
    "departmentOffice": "വകുപ്പ് / ഓഫീസ്",
    "departmentPlaceholder": "ഉദാ. Regional Passport Office",
    "officeAddress": "ഓഫീസ് വിലാസം / പ്രദേശം",
    "officeAddressPlaceholder": "ബിൽഡിംഗ്, തെരുവ്, നഗരം അല്ലെങ്കിൽ ജില്ല",
    "serviceWork": "എന്ത് സേവനം അല്ലെങ്കിൽ ജോലി സംബന്ധിച്ചിരുന്നതാണ്?",
    "servicePlaceholder": "ഉദാ. Building permit, licence renewal, pension file",
    "whatDemanded": "ഏതൊക്കെ ആവശ്യപ്പെട്ടിഒന്ന",
    "amountPaid": "ആവശ്യപ്പെട്ട / നൽകിയ തുക (₹)",
    "amountPlaceholder": "ഉദാ. 2000",
    "paymentForm": "പണമിടപാട് രീതി",
    "cash": "പണം",
    "upi": "UPI / ഓൺലൈൻ ട്രാൻസ്ഫർ",
    "bankTransfer": "ബാങ്ക് ട്രാൻസ്ഫർ",
    "giftGoods": "പരിഹാരം അല്ലെങ്കിൽ സാധനങ്ങൾ",
    "favourBenefit": "നന്മയോ മറ്റേതെങ്കിലും ഫലം",
    "demandMaker": "ആവശ്യപ്പെടുന്നത് ആരായിരുന്നു?",
    "officialPersonally": "അധികാരി വ്യക്തിപരമായി",
    "intermediary": "മധ്യസ്ഥൻ / ഏജൻറ് / മിഡിൽമാൻ",
    "both": "രണ്ടും",
    "witnessDetails": "സാക്ഷികളുടെ / മധ്യസ്ഥരുടെ വിശദാംശങ്ങൾ",
    "witnessPlaceholder": "നാമങ്ങളും ബന്ധപ്പെടാനുള്ള വിവരങ്ങളും, ഉണ്ടായെങ്കിൽ",
    "dateDemand": "ആവശ്യപ്പെട്ട തീയതി",
    "timeApprox": "സമയം (ഏകദേശം)",
    "placeDemand": "ആവശ്യപ്പെട്ട സ്ഥലത്തെ സ്ഥലം",
    "placePlaceholder": "ഉദാ. കൗണ്ടർ 4, ഓഫീസ് ഗേറ്റ്, ഫോൺ ഉപയോഗിച്ച്",
    "factsLabel": "അധികാരി എന്തൊക്കെയാണോ പറഞ്ഞത് അല്ലെങ്കിൽ ചെയ്തത് (വസ്തുതകൾ മാത്രം)",
    "factsPlaceholder": "ഏത് ക്രമത്തിൽ അത് പറയലായതോ ചെയ്തതോ ഉണ്ടോ അതു നിശ്ചയമായി വിവരിക്കുക.",
    "evidenceLabel": "സാക്ഷ്യങ്ങളും സന്ദർഭ വിശദാംശങ്ങളും",
    "evidencePlaceholder": "സന്ദേശങ്ങൾ, ഫോൺ നമ്പറുകൾ, ഇമെയിലുകൾ, നോട്ടിസുകൾ, റസീറ്റ്‌లు, സ്‌ക്രീൻഷോട്ടുകൾ അല്ലെങ്കിൽ ഇടപാട് വിവരം",
    "referenceLabel": "അപേക്ഷ / ഫയൽ / ലൈസൻസ് റഫറൻസ് നമ്പർ",
    "referencePlaceholder": "ഉദാ. Application No. 12345/2026",
    "finalReview": "അവസാന അവലോകനം",
    "analysing": "വിശകലനം ചെയ്‌തു കൊണ്ടിരിക്കുന്നു…",
    "exactWebsite": "സൂക്ഷ്മമായ വെബ്സൈറ്റ് കണ്ടെത്തുക",
    "runAssistant": "സമർപ്പിക്കുന്നതിന് മുൻപ് AI സഹായകൻ പ്രവർത്തിപ്പിക്കുക",
    "submitComplaint": "പരാതി സമർപ്പിക്കുക",
    "continue": "തുടരുക",
    "back": "മുക്ക് പുറകെ",
    "securityCheck": "സുരക്ഷാ പരിശോധന: 7 + 4 നൽകുക",
    "successRedirect": "നിങ്ങളുടെ പരാതി രേഖപ്പെടുത്തപ്പെട്ടു. സൂക്ഷ്മ ഔദ്യോഗിക ഗതി തുറക്കുന്നു…",
    "openOfficial": "സൂക്ഷ്മ ഔദ്യോഗിക വെബ്സൈറ്റ് തുറക്കുക",
    "seeOfficer": "മേൽപറഞ്ഞ ഉദ്യോഗസ്ഥനെ കാണുക",
    "officialDestination": "തെറ്റുമായOfficial ഗതി തിരഞ്ഞെടുത്ത്",
    "education": "വിദ്യാഭ്യാസം",
    "backPortal": "പോർട്ടലിലേക്ക് മടങ്ങുക",
    "useGuide": "ഇതിനെ മാർഗ്ഗദർശകമായായി ഉപയോഗിക്കുക",
    "safetyReminder": "സുരക്ഷാ ഓർമ്മിപ്പ്"
  },
  "mni": {
    "fullName": "ꯄꯣꯏ ꯂꯣꯟꯁꯤꯡ",
    "yourFullName": "ꯁꯤꯡꯄꯥꯛ ꯄꯣꯏ ꯂꯣꯟꯁꯤꯡ",
    "mobileNumber": "ꯃꯣꯕꯤꯂ ꯅꯥꯔꯤ",
    "tenDigitMobile": "10-ꯗꯤꯒꯇ ꯃꯣꯕꯤꯂ",
    "emailOptional": "ଇମେଇଲ (ꯑꯣꯕସନাল)",
    "emailPlaceholder": "you@example.com",
    "addressCityOptional": "ꯑꯦꯑꯔେꯁ / ꯁꯤꯇꯤ (ꯑꯣꯕସନাল)",
    "whereAgenciesReach": "ꯑꯦꯛꯂꯦꯝ ꯑꯣꯔꯀꯤꯗꯥ ꯑꯃꯥ ꯑꯣꯏꯂꯥ ꯃꯇꯝꯕꯤ",
    "idType": "ID ꯇꯞꯄꯤ",
    "voterId": "ꯄꯣꯠꯔ ID",
    "pan": "PAN",
    "drivingLicence": "ꯗ꯭ꯔାଇଭିଂ ଲାଇସେନସ্",
    "idNumber": "ID ꯅꯨꯝꯕꯦ",
    "enterIdNumber": "ID ꯅꯨꯝꯕꯦ ꯃꯩꯅꯕ",
    "oneTimePassword": "ওন-টাইম ପାସୱର୍ଡ",
    "otpPlaceholder": "6-ꯗꯤꯒꯇ OTP",
    "sending": "ꯁꯦꯟꯗିꯑꯟ…",
    "sendOtp": "OTP পঠাও",
    "checking": "ꯀꯤꯡꯀꯤꯏꯡ…",
    "verifyOtp": "OTP ꯑꯦꯣꯕେୟମ",
    "phoneVerified": "ফোন ꯄꯦরীফାଇড",
    "reportAnonymously": "নামশূণ্যভাৱে ৰিপোর্ট কৰক",
    "noIdentityRequired": "নাম, ফোন বা ID প্রয়োজন নহয়। আপুনি একটী ট্র্যাকিং ID পাইব।",
    "select": "নির্বাচন কৰক",
    "whoAsked": "কোনে ৰেয়াত বা ঘুষ বিচাৰিলে/ল'লে?",
    "centralEmployee": "কেন্দ্রীয় চৰকাৰী কৰ্মচাৰী / PSU / বেংক",
    "stateEmployee": "ৰাজ্য চৰকাৰ বা স্থানীয় সংস্থাৰ কৰ্মচাৰী",
    "policeVigilance": "পুলিচ বা ভিজিলেন্সৰ কৰ্মী",
    "onlineDemand": "অনলাইন / ফোন / UPI দাবী",
    "notSure": "নিশ্চিত নহয়",
    "officialName": "অফিচিয়ালৰ নাম (জানিলে)",
    "officialNamePlaceholder": "e.g. Ramesh Verma",
    "designation": "পদবী",
    "designationPlaceholder": "e.g. Clerk, Inspector",
    "departmentOffice": "বিভাগ / কাৰ্যালয়",
    "departmentPlaceholder": "e.g. Regional Passport Office",
    "officeAddress": "কাৰ্যালয়ৰ ঠিকনা / এলাকা",
    "officeAddressPlaceholder": "Building, street, city or district",
    "serviceWork": "কোন সেৱা বা কাম জড়িত আছিল?",
    "servicePlaceholder": "e.g. Building permit, licence renewal, pension file",
    "whatDemanded": "কি দাবী কৰা হৈছিল",
    "amountPaid": "দাবী/পইচা (₹)",
    "amountPlaceholder": "e.g. 2000",
    "paymentForm": "পেমেন্টৰ ৰূপ",
    "cash": "নগদ",
    "upi": "UPI / অনলাইন স্থানান্তৰ",
    "bankTransfer": "ব্যাংক স্থানান্তৰ",
    "giftGoods": "উপহাৰ বা সামগ্ৰী",
    "favourBenefit": "পাৰিতোষিক বা অন্য সুবিধা",
    "demandMaker": "কোনে দাবী কৰিছিল?",
    "officialPersonally": "অফিচিয়ালে ব্যক্তিগতভাৱে",
    "intermediary": "এজন মধ্যস্থ/এজেণ্ট/মিডলমেন",
    "both": "দুয়োটা",
    "witnessDetails": "সাক্ষী / মধ্যস্থৰ বিৱৰণ",
    "witnessPlaceholder": "নাম আৰু যোগাযোগ, থাকিলে",
    "dateDemand": "দাবীৰ তাৰিখ",
    "timeApprox": "সময় (অনুমান)",
    "placeDemand": "দাবী কৰা স্থান",
    "placePlaceholder": "e.g. Counter 4, office gate, over phone",
    "factsLabel": "অফিচিয়ালে কি কৈছিল বা কৰিছিল (কেৱল তথ্য)",
    "factsPlaceholder": "কেন্দ্ৰকৰি ঠিক কি কৈছিল বা কাৰ্য্য কৰা হৈছিল, ক্ৰমে বৰ্ণনা কৰক।",
    "evidenceLabel": "প্ৰমাণ আৰু ৰেফাৰেঞ্চ বিৱৰণ",
    "evidencePlaceholder": "মেছেজ, ফোন নম্বৰ, ইমেইল, নোটিছ, ৰিছিট, ষ্ক্ৰীণশট বা লেনদেনৰ বিশদ",
    "referenceLabel": "আবেদন / ফাইল / লাইচেঞ্চ ৰেফাৰেঞ্চ নম্বৰৰ",
    "referencePlaceholder": "e.g. Application No. 12345/2026",
    "finalReview": "চূড়ান্ত পৰ্যালোচনা",
    "analysing": "বিশ্লেষণ কৰা হ'ল…",
    "exactWebsite": "ঠিক কোন ৱেবছাইটটো খুজক",
    "runAssistant": "জমা কৰাৰ আগতে AI সহায়ক চলাওক",
    "submitComplaint": "অভিযোগ দাখিল কৰক",
    "continue": "অগ্ৰসৰ হওক",
    "back": "ফিৰা",
    "securityCheck": "নিরাপত্তা পৰীক্ষা: 7 + 4 লিখক",
    "successRedirect": "আপোনাৰ অভিযোগ দাখিল কৰা হ’ল। সঠিক কাৰ্য্যালয় খোলাটো আৰম্ভ হৈছে…",
    "openOfficial": "ঠিক সেই চৰকাৰী ৱেবছাইট খোলক",
    "seeOfficer": "উপৰে উল্লিখিত বিষয়ক অৱহিত কৰ্মীৰ ਵੇৰাও",
    "officialDestination": "ঠিক চৰকাৰী গন্তব্য বাছনি কৰক",
    "education": "শিক্ষা",
    "backPortal": "প'ৰ্টেললৈ উভতি যাওক",
    "useGuide": "এহাল গাইড হিচাপে ব্যৱহাৰ কৰক",
    "safetyReminder": "সুৰক্ষাৰ স্মৰণ"
  },
  "mr": {
    "fullName": "पूरा नाव",
    "yourFullName": "आपले पूर्ण नाव",
    "mobileNumber": "मोबाइल नंबर",
    "tenDigitMobile": "10-अंकी मोबाइल",
    "emailOptional": "ईमेल (ऐच्छिक)",
    "emailPlaceholder": "you@example.com",
    "addressCityOptional": "पत्ता / शहर (ऐच्छिक)",
    "whereAgenciesReach": "एजन्सी आपल्यापर्यंत कशी पोहोचू शकतात",
    "idType": "ओळख प्रकार",
    "voterId": "मतदार ओळखपत्र",
    "pan": "PAN",
    "drivingLicence": "ड्रायव्हिंग लायसन्स",
    "idNumber": "ओळख क्रमांक",
    "enterIdNumber": "ओळख क्रमांक भरा",
    "oneTimePassword": "वन-टाइम पासवर्ड",
    "otpPlaceholder": "6-अंकी OTP",
    "sending": "पाठवत आहे…",
    "sendOtp": "OTP पाठवा",
    "checking": "तपासत आहे…",
    "verifyOtp": "OTP पडताळा",
    "phoneVerified": "फोन पडताळले गेले",
    "reportAnonymously": "अनामिकरित्या अहवाल द्या",
    "noIdentityRequired": "नाव, फोन किंवा ओळखपत्र आवश्यक नाही. आपल्याला एक ट्रॅकिंग ID मिळेल.",
    "select": "निवडा",
    "whoAsked": "कुणी लंचन/घूस मागितली/घेतली?",
    "centralEmployee": "केंद्रीय शासन कर्मचारी / PSU / बँक",
    "stateEmployee": "राज्य शासन किंवा स्थानिक संस्था कर्मचारी",
    "policeVigilance": "पोलीस किंवा चौकशी कर्मचारी",
    "onlineDemand": "ऑनलाइन / फोन / UPI मागणी",
    "notSure": "निश्चित नाही",
    "officialName": "अधिकाऱ्याचे नाव (माहीत असल्यास)",
    "officialNamePlaceholder": "e.g. Ramesh Verma",
    "designation": "पद",
    "designationPlaceholder": "e.g. Clerk, Inspector",
    "departmentOffice": "विभाग / कार्यालय",
    "departmentPlaceholder": "e.g. Regional Passport Office",
    "officeAddress": "कार्यालयाचा पत्ता / क्षेत्र",
    "officeAddressPlaceholder": "Building, street, city or district",
    "serviceWork": "कुठली सेवा किंवा काम समाविष्ट होते?",
    "servicePlaceholder": "e.g. Building permit, licence renewal, pension file",
    "whatDemanded": "काय मागितले गेले",
    "amountPaid": "मागणी / दिली रक्कम (₹)",
    "amountPlaceholder": "e.g. 2000",
    "paymentForm": "देयक प्रकार",
    "cash": "रोख",
    "upi": "UPI / ऑनलाइन ट्रान्सफर",
    "bankTransfer": "बँक हस्तांतरण",
    "giftGoods": "भेट किंवा वस्तू",
    "favourBenefit": "अनुकूलता किंवा इतर लाभ",
    "demandMaker": "कोणाने मागणी केली?",
    "officialPersonally": "अधिकारी स्वतःने",
    "intermediary": "मध्यस्थ / एजंट / वरचढ व्यक्ती",
    "both": "दोन्ही",
    "witnessDetails": "साक्षीदार / मध्यस्थ माहिती",
    "witnessPlaceholder": "नावे आणि संपर्क, असल्यास",
    "dateDemand": "मागणीची तारीख",
    "timeApprox": "वेळ (सुमारे)",
    "placeDemand": "मागणी केलेले स्थान",
    "placePlaceholder": "e.g. Counter 4, office gate, over phone",
    "factsLabel": "अधिकाऱ्याने काय सांगितले किंवा केले (केवळ तथ्ये)",
    "factsPlaceholder": "नेमके काय सांगितले किंवा केले, क्रमाने वर्णन करा.",
    "evidenceLabel": "पुरावे आणि संदर्भ माहिती",
    "evidencePlaceholder": "मेसेजेस, फोन नंबर, ईमेल, नोटिस, पावत्या, स्क्रीनशॉट किंवा व्यवहार तपशील",
    "referenceLabel": "अर्ज / फाईल / परवानगी संदर्भ क्रमांक",
    "referencePlaceholder": "e.g. Application No. 12345/2026",
    "finalReview": "अंतिम पुनरावलोकन",
    "analysing": "विश्लेषित करत आहे…",
    "exactWebsite": "अचूक वेबसाइट शोधा",
    "runAssistant": "सबमिट करण्यापूर्वी AI सहाय्यक चालवा",
    "submitComplaint": "तक्रार सादर करा",
    "continue": "सुरू ठेवा",
    "back": "मागे",
    "securityCheck": "सुरक्षा तपासणी: 7 + 4 लिहा",
    "successRedirect": "आपली तक्रार नोंदवली गेली आहे. अचूक अधिकृत गंतव्य उघडले जात आहे…",
    "openOfficial": "अचूक अधिकृत वेबसाइट उघडा",
    "seeOfficer": "वरील अधिकारी पहा",
    "officialDestination": "योग्य अधिकृत गंतव्य निवडा",
    "education": "शिक्षण",
    "backPortal": "पोर्टलवर परत जा",
    "useGuide": "हे मार्गदर्शन म्हणून वापरा",
    "safetyReminder": "सुरक्षा आठवण"
  },
  "ne": {
    "fullName": "पूरा नाम",
    "yourFullName": "तपाईंको पूरा नाम",
    "mobileNumber": "मोबाइल नम्बर",
    "tenDigitMobile": "10-अंक मोबाइल",
    "emailOptional": "इमेल (ऐच्छिक)",
    "emailPlaceholder": "you@example.com",
    "addressCityOptional": "ठेगाना / शहर (ऐच्छिक)",
    "whereAgenciesReach": "संस्थाहरू तपाईंलाई कहाँ सम्पर्क गर्न सक्छन्",
    "idType": "पहिचान प्रकार",
    "voterId": "मतदाता परिचय पत्र",
    "pan": "PAN",
    "drivingLicence": "ड्राइविङ लाइसेन्स",
    "idNumber": "ID नम्बर",
    "enterIdNumber": "ID नम्बर लेख्नुहोस्",
    "oneTimePassword": "वन-टाइम पासवर्ड",
    "otpPlaceholder": "6-अंक OTP",
    "sending": "पठाउँदै…",
    "sendOtp": "OTP पठाउनुहोस्",
    "checking": "जाँच्दै…",
    "verifyOtp": "OTP सत्यापित गर्नुहोस्",
    "phoneVerified": "फोन पुष्टि गरिएको",
    "reportAnonymously": "नामी नखुलाइ रिपोर्ट गर्नुहोस्",
    "noIdentityRequired": "नाम, फोन वा ID आवश्यक छैन। तपाईंले ट्र्याकिङ ID प्राप्त गर्नुहुनेछ।",
    "select": "छान्नुहोस्",
    "whoAsked": "कसले घुस माग्यो वा लियो?",
    "centralEmployee": "केन्द्र सरकार कर्मचारी / PSU / बैंक",
    "stateEmployee": "राज्य सरकार वा स्थानीय संस्था कर्मचारी",
    "policeVigilance": "प्रहरी वा निगरानी कर्मचारी",
    "onlineDemand": "अनलाइन / फोन / UPI माग",
    "notSure": "निश्चित छैन",
    "officialName": "अधिकृतको नाम (थाह भएमा)",
    "officialNamePlaceholder": "e.g. Ramesh Verma",
    "designation": "पद",
    "designationPlaceholder": "e.g. Clerk, Inspector",
    "departmentOffice": "विभाग / कार्यालय",
    "departmentPlaceholder": "e.g. Regional Passport Office",
    "officeAddress": "कार्यालय ठेगाना / क्षेत्र",
    "officeAddressPlaceholder": "Building, street, city or district",
    "serviceWork": "कुन सेवा वा काम संलग्न थियो?",
    "servicePlaceholder": "e.g. Building permit, licence renewal, pension file",
    "whatDemanded": "के मागियो",
    "amountPaid": "मागिएको/तिरिएको रकम (₹)",
    "amountPlaceholder": "e.g. 2000",
    "paymentForm": "भुक्तानी प्रकार",
    "cash": "नगद",
    "upi": "UPI / अनलाइन ट्रान्सफर",
    "bankTransfer": "बैंक ट्रान्सफर",
    "giftGoods": "उपहार वा सामान",
    "favourBenefit": "पक्ष वा अन्य लाभ",
    "demandMaker": "कसले माग्यो?",
    "officialPersonally": "अधिकृतले व्यक्तिगत रूपमा",
    "intermediary": "एजेन्ट / बिचौलिया",
    "both": "दुवै",
    "witnessDetails": "साक्षी/बिचौलियाको विवरण",
    "witnessPlaceholder": "नाम र सम्पर्क, भएमा",
    "dateDemand": "मागेको मिति",
    "timeApprox": "समय (अनुमानित)",
    "placeDemand": "माग गरिएको स्थान",
    "placePlaceholder": "e.g. Counter 4, office gate, over phone",
    "factsLabel": "अधिकृतले के भने वा गरे (केवल तथ्य)",
    "factsPlaceholder": "ठ्याक्कै के भनियो वा गरियो, क्रमशः वर्णन गर्नुहोस्।",
    "evidenceLabel": "प्रमाण र सन्दर्भ विवरण",
    "evidencePlaceholder": "सन्देशहरू, फोन नम्बर, इमेल, सूचनाहरू, रसिदहरू, स्क्रिनसट वा लेनदेन विवरण",
    "referenceLabel": "आवेदन / फाइल / लाइसेन्स सन्दर्भ नम्बर",
    "referencePlaceholder": "e.g. Application No. 12345/2026",
    "finalReview": "अन्तिम समीक्षा",
    "analysing": "विश्लेषण गर्दै…",
    "exactWebsite": "ठ्याक्कै वेबसाइट खोज्नुहोस्",
    "runAssistant": "बुझाउनुअघि AI सहायक चलाउनुहोस्",
    "submitComplaint": "गुनासो पेश गर्नुहोस्",
    "continue": "जारी राख्नुहोस्",
    "back": "पछाडि",
    "securityCheck": "सुरक्षा जाँच: 7 + 4 लेख्नुहोस्",
    "successRedirect": "तपाईंको गुनासो दर्ता गरिएको छ। ठ्याक्कै आधिकारिक गन्तव्य खोल्दैछ…",
    "openOfficial": "ठ्याक्कै आधिकारिक वेबसाइट खोल्नुहोस्",
    "seeOfficer": "माथिको अधिकारी देखें",
    "officialDestination": "सही आधिकारिक गन्तव्य छान्नुहोस्",
    "education": "शिक्षा",
    "backPortal": "पोर्टलमा फर्कनुहोस्",
    "useGuide": "यसलाई मार्गदर्शकको रूपमा प्रयोग गर्नुहोस्",
    "safetyReminder": "सुरक्षा सम्झना"
  },
  "or": {
    "fullName": "ସମ୍ପୂର୍ଣ୍ଣ ନାମ",
    "yourFullName": "ଆପଣଙ୍କର ସମ୍ପୂର୍ଣ୍ଣ ନାମ",
    "mobileNumber": "ମୋବାଇଲ୍ ନମ୍ବର",
    "tenDigitMobile": "10-ଅଙ୍କର ମୋବାଇଲ୍",
    "emailOptional": "ଇମେଲ୍ (ଇଚ୍ଛାନୁସାରେ)",
    "emailPlaceholder": "you@example.com",
    "addressCityOptional": "ଠିକଣା / ସହର (ଇଚ୍ଛାନୁସାରେ)",
    "whereAgenciesReach": "ଏଜେନ୍ସୀଗୁଡ଼ିକ କେଉଁଠି ଆପଣଙ୍କୁ ପହଁଚିପାରିବେ",
    "idType": "ଆଇ.ଡି. ପ୍ରକାର",
    "voterId": "ମତଦାତା ପତ୍ର",
    "pan": "PAN",
    "drivingLicence": "ଡ୍ରାଇଭିଂ ଲାଇସେନ୍ସ",
    "idNumber": "ଆଇଡି ନମ୍ବର",
    "enterIdNumber": "ଆଇଡି ନମ୍ବର ପ୍ରବେଶ କରନ୍ତୁ",
    "oneTimePassword": "ୱନ-ଟାଇମ୍ ପାସୱର୍ଡ",
    "otpPlaceholder": "6-ଅଙ୍କ OTP",
    "sending": "ପଠାଯାଉଛି…",
    "sendOtp": "OTP ପଠାନ୍ତୁ",
    "checking": "ଯାଞ୍ଚ…",
    "verifyOtp": "OTP ସତ୍ୟାପନ କରନ୍ତୁ",
    "phoneVerified": "ଫୋନ୍ ସତ୍ୟାପିତ",
    "reportAnonymously": "ଗୁପ୍ତଭାବେ ରିପୋର୍ଟ କରନ୍ତୁ",
    "noIdentityRequired": "ନାମ, ଫୋନ୍ କିମ୍ବା ଆଇଡି ଆବଶ୍ୟକ ନୁହେଁ। ଆପଣଙ୍କୁ ଏକ ଟ୍ର୍ୟାକିଂ ID ମିଳିବ।",
    "select": "ଚୟନ କରନ୍ତୁ",
    "whoAsked": "କିଏ ଘୁଷ/ମାଗଣା ଚାହାଁଲା କିମ୍ବା ନେଲେ?",
    "centralEmployee": "କେନ୍ଦ୍ରୀୟ ସରକାର କର୍ମଚାରୀ / PSU / ବ୍ୟାଙ୍କ",
    "stateEmployee": "ରାଜ୍ୟ ସରକାର କିମ୍ବା ସ୍ଥାନୀୟ ସଂସ୍ଥା କର୍ମଚାରୀ",
    "policeVigilance": "ପୋଲିସ କିମ୍ବା ଜରୂରୀ ନିରୀକ୍ଷଣ କର୍ମଚାରୀ",
    "onlineDemand": "ଅନଲାଇନ୍ / ଫୋନ୍ / UPI ଦାବୀ",
    "notSure": "ନିଶ୍ଚିତ ନୁହେଁ",
    "officialName": "ଅଧିକାରୀଙ୍କ ନାମ (ଜାଣିଥିଲେ)",
    "officialNamePlaceholder": "e.g. Ramesh Verma",
    "designation": "ପଦବୀ",
    "designationPlaceholder": "e.g. Clerk, Inspector",
    "departmentOffice": "ବିଭାଗ / କାର୍ଯ୍ୟାଳୟ",
    "departmentPlaceholder": "e.g. Regional Passport Office",
    "officeAddress": "କାର୍ଯ୍ୟାଳୟ ଠିକଣା / ଅଞ୍ଚଳ",
    "officeAddressPlaceholder": "Building, street, city or district",
    "serviceWork": "କେଉଁ ସେବା କିମ୍ବା କାମ ସମ୍ପୃକ୍ତ ଥିଲା?",
    "servicePlaceholder": "e.g. Building permit, licence renewal, pension file",
    "whatDemanded": "କ'ଣ ଦାବି କରାଗଲା",
    "amountPaid": "ଦାବି/ଦିଆ ରାଶି (₹)",
    "amountPlaceholder": "e.g. 2000",
    "paymentForm": "ଦେୟ ପ୍ରକାର",
    "cash": "ଟକା",
    "upi": "UPI / ଅନଲାଇନ୍ ଟ୍ରାନ୍ସଫର୍",
    "bankTransfer": "ବ୍ୟାଙ୍କ ଟ୍ରାନ୍ସଫର୍",
    "giftGoods": "ଉପହାର କିମ୍ବା ସାମଗ୍ରୀ",
    "favourBenefit": "ପକ୍ଷପାତ କିମ୍ବା ଅନ୍ୟ ଲାଭ",
    "demandMaker": "କିଏ ଦାବି କଲା?",
    "officialPersonally": "ଅଧିକାରୀ ନିଜେ",
    "intermediary": "ମଧ୍ୟସ୍ଥ/ଏଜେଣ୍ଟ/ମିଡଲମ୍ୟାନ୍",
    "both": "ଦୁହେଁ",
    "witnessDetails": "ସାକ୍ଷୀ / ମଧ୍ୟସ୍ଥର ବିବରଣୀ",
    "witnessPlaceholder": "ନାମ ଓ ସମ୍ପର୍କ, ଯଦି ଥାଏ",
    "dateDemand": "ଦାବିର ତାରିଖ",
    "timeApprox": "ସମୟ (ଆନୁମାନିକ)",
    "placeDemand": "ଯେଉଁଥିଏ ଦାବି କରାଗଲା ସ୍ଥଳ",
    "placePlaceholder": "e.g. Counter 4, office gate, over phone",
    "factsLabel": "ଅଧିକାରୀ କଣ କହିଥିଲେ କିମ୍ବା କଣ କଲେ (କେବଳ ତଥ୍ୟ)",
    "factsPlaceholder": "ସଠିକ୍ ଭାବରେ କଣ କହାଗଲା ବା କରାଗଲା, କ୍ରମେ ବର୍ଣ୍ଣନା କରନ୍ତୁ।",
    "evidenceLabel": "ପ୍ରମାଣ ଏବଂ ସନ୍ଦର୍ଭ ବିବରଣୀ",
    "evidencePlaceholder": "ମେସେଜ୍, ଫୋନ୍ ନମ୍ବର, ଇମେଲ୍, ନୋଟିସ୍, ରସିଦ୍, ସ୍କ୍ରିନସଟ୍ କିମ୍ବା ଲେନଦେନ ବିବରଣୀ",
    "referenceLabel": "ଆବେଦନ/ଫାଇଲ୍/ଲାଏସେନ୍ସ ସନ୍ଦର୍ଭ ନମ୍ବର",
    "referencePlaceholder": "e.g. Application No. 12345/2026",
    "finalReview": "ଅନ୍ତିମ ସମୀକ୍ଷା",
    "analysing": "ବିଶ୍ଲେଷଣ କରାଯାଉଛି…",
    "exactWebsite": "ଠିକ୍ ୱେବସାଇଟ୍ ଖୋଜନ୍ତୁ",
    "runAssistant": "ଦାଖଲ ପୂର୍ବେ AI ସହାୟକ ଚଲାନ୍ତୁ",
    "submitComplaint": "ଅଭିଯୋଗ ପ୍ରଦାନ କରନ୍ତୁ",
    "continue": "ଚାଲୁ ରଖନ୍ତୁ",
    "back": "ପଛକୁ",
    "securityCheck": "ସୁରକ୍ଷା ପରୀକ୍ଷା: 7 + 4 ଲେଖନ୍ତୁ",
    "successRedirect": "ଆପଣଙ୍କର ଅଭିଯୋଗ ଦାଖଲ ହୋଇଛି। ଠିକ୍ ସରକାରୀ ଗନ୍ତବ୍ୟ ଖୋଲାଯାଉଛି…",
    "openOfficial": "ଠିକ୍ ସରକାରୀ ଭେବସାଇଟ୍ ଖୋଲନ୍ତୁ",
    "seeOfficer": "ଉପରେ ଦିଆଯାଇଥିବା କର୍ମଚାରୀକୁ ଦେଖନ୍ତୁ",
    "officialDestination": "ଠିକ୍ ସରକାରୀ ଗନ୍ତବ୍ୟ ଚୟନ କରନ୍ତୁ",
    "education": "ଶିକ୍ଷା",
    "backPortal": "ପୋର୍ଟାଲକୁ ପଛକୁ ଯାଆନ୍ତୁ",
    "useGuide": "ମାର୍ଗଦର୍ଶନ ଭାବରେ ଏହା ବ୍ୟବହାର କରନ୍ତୁ",
    "safetyReminder": "ସୁରକ୍ଷା ସ୍ମରଣୀ"
  },
  "pa": {
    "fullName": "ਪੂਰਾ ਨਾਮ",
    "yourFullName": "ਤੁਹਾਡਾ ਪੂਰਾ ਨਾਮ",
    "mobileNumber": "ਮੋਬਾਈਲ ਨੰਬਰ",
    "tenDigitMobile": "10-ਅੰਕ ਮੋਬਾਈਲ",
    "emailOptional": "ਈਮੇਲ (ਵਿਕਲਪਿਕ)",
    "emailPlaceholder": "you@example.com",
    "addressCityOptional": "ਪਤਾ / ਸ਼ਹਿਰ (ਵਿਕਲਪਿਕ)",
    "whereAgenciesReach": "ਏਜੰਸੀਆਂ ਤੁਹਾਡੇ ਤੱਕ ਕਿੱਥੇ ਪਹੁੰਚ ਸਕਦੀਆਂ ਹਨ",
    "idType": "ਪਛਾਣ ਕਿਸਮ",
    "voterId": "ਵੋਟਰ ID",
    "pan": "PAN",
    "drivingLicence": "ਡ੍ਰਾਈਵਿੰਗ ਲਾਇਸੈਂਸ",
    "idNumber": "ID ਨੰਬਰ",
    "enterIdNumber": "ID ਨੰਬਰ ਦਰਜ ਕਰੋ",
    "oneTimePassword": "ਵਨ-ਟਾਈਮ ਪਾਸਵਰਡ",
    "otpPlaceholder": "6-ਅੰਕ OTP",
    "sending": "ਭੇਜ ਰਿਹਾ ਹੈ…",
    "sendOtp": "OTP ਭੇਜੋ",
    "checking": "ਚੈੱਕ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ…",
    "verifyOtp": "OTP ਸાનીਖੇ",
    "phoneVerified": "ਫੋਨ ਸੱਚਿਆ ਗਿਆ",
    "reportAnonymously": "ਅਗਿਆਤ ਰੂਪ ਵਿੱਚ ਰਿਪੋਰਟ ਕਰੋ",
    "noIdentityRequired": "ਨਾਂ, ਫੋਨ ਜਾਂ ID ਦੀ ਲੋੜ ਨਹੀਂ। ਤੁਹਾਨੂੰ ਇੱਕ ਟ੍ਰੈਕਿੰਗ ID ਮਿਲੇਗੀ।",
    "select": "ਚੁਣੋ",
    "whoAsked": "ਕਿਸ ਨੇ ਰਿਸ਼ਵਤ ਮੰਗੀ ਜਾਂ ਲਈ?",
    "centralEmployee": "ਕੇਂਦਰੀ ਸਰਕਾਰ ਕਿਰਮਚਾਰੀ / PSU / ਬੈਂਕ",
    "stateEmployee": "ਰਾਜ ਸਰਕਾਰ ਜਾਂ ਸਥਾਨਕ ਬਾਡੀ ਕਰਮਚਾਰੀ",
    "policeVigilance": "ਪੁਲਿਸ ਜਾਂ ਵਿੱਜਿਲੈਂਸ ਕਰਮਚਾਰੀ",
    "onlineDemand": "ਆਨਲਾਈਨ / ਫ਼ੋਨ / UPI ਮੰਗ",
    "notSure": "ਪੱਕਾ ਨਹੀਂ",
    "officialName": "ਅਧਿਕਾਰੀ ਦਾ ਨਾਮ (ਜੇ ਪਤਾ ਹੋਵੇ)",
    "officialNamePlaceholder": "e.g. Ramesh Verma",
    "designation": "ਪਦ",
    "designationPlaceholder": "e.g. Clerk, Inspector",
    "departmentOffice": "ਵਿਭਾਗ / ਦਫਤਰ",
    "departmentPlaceholder": "e.g. Regional Passport Office",
    "officeAddress": "ਦਫਤਰ ਦਾ ਪਤਾ / ਇਲਾਕਾ",
    "officeAddressPlaceholder": "Building, street, city or district",
    "serviceWork": "ਕਿਹੜੀ ਸੇਵਾ ਜਾਂ ਕੰਮ ਵਿੱਚ ਸ਼ਾਮਲ ਸੀ?",
    "servicePlaceholder": "e.g. Building permit, licence renewal, pension file",
    "whatDemanded": "ਕੀ ਮੰਗੀ ਗਈ",
    "amountPaid": "ਮੰਗੀ ਗਈ / ਦਿੱਤੀ ਰਕਮ (₹)",
    "amountPlaceholder": "e.g. 2000",
    "paymentForm": "ਭੁਗਤਾਨ ਦਾ ਰੂਪ",
    "cash": "ਨਕਦ",
    "upi": "UPI / ਆਨਲਾਈਨ ਟ੍ਰਾਂਸਫਰ",
    "bankTransfer": "ਬੈਂਕ ਟ੍ਰਾਂਸਫਰ",
    "giftGoods": "ਤੋਹਫਾ ਜਾਂ ਸਾਮਾਨ",
    "favourBenefit": "ਪਸੰਦ ਜਾਂ ਹੋਰ ਲਾਭ",
    "demandMaker": "ਕਿਸ ਨੇ ਮੰਗ ਕੀਤੀ?",
    "officialPersonally": "ਅਧਿਕਾਰੀ ਨੇ ਖੁਦ",
    "intermediary": "ਮੱਧਸਥ/ਏਜੰਟ/ਦਿਲਾਸਾ ਕਰਨ ਵਾਲਾ",
    "both": "ਦੋਹਾਂ",
    "witnessDetails": "ਗਵਾਹ/ਮੱਧਸਥ ਵੇਰਵਾ",
    "witnessPlaceholder": "ਨਾਂਅ ਅਤੇ ਸੰਪਰਕ, ਜੇ ਹੋਵੇ",
    "dateDemand": "ਮੰਗ ਦੀ ਤਾਰੀਖ",
    "timeApprox": "ਸਮਾਂ (ਅਨੁਮਾਨ)",
    "placeDemand": "ਜਗ੍ਹਾ ਜਿੱਥੇ ਮੰਗ ਕੀਤੀ ਗਈ",
    "placePlaceholder": "e.g. Counter 4, office gate, over phone",
    "factsLabel": "ਅਧਿਕਾਰੀ ਨੇ ਕੀ ਕਿਹਾ ਜਾਂ ਕੀਤਾ (ਕੇਵਲ ਤੱਥ)",
    "factsPlaceholder": "ਬਿਲਕੁਲ ਕੀ ਕਿਹਾ ਜਾਂ ਕੀਤਾ ਗਿਆ, ਕ੍ਰਮਵਾਰ ਵਰਣਨ ਕਰੋ।",
    "evidenceLabel": "ਸਬੂਤ ਅਤੇ ਸੰਦਰਭ ਵੇਰਵਾ",
    "evidencePlaceholder": "ਸੁਨੇਹੇ, ਫੋਨ ਨੰਬਰ, ਈਮੇਲ, ਨੋਟਿਸ, ਰਸੀਦਾਂ, ਸਕਰੀਨਸ਼ਾਟ ਜਾਂ ਲੈਣਦੈਣ ਵੇਰਵੇ",
    "referenceLabel": "ਆਵেদন / ਫਾਈਲ / ਲਾਇਸੈਂਸ ਸੰਦਰਭ ਨੰਬਰ",
    "referencePlaceholder": "e.g. Application No. 12345/2026",
    "finalReview": "ਅੰਤਿਮ ਸਮੀਖਿਆ",
    "analysing": "ਵਿਸ਼ਲੇਸ਼ਣ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ…",
    "exactWebsite": "ਨਿਰਧਾਰਤ ਵੈਬਸਾਈਟ ਲੱਭੋ",
    "runAssistant": "ਜਮ੍ਹਾਂ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ AI ਸਹਾਇਕ ਚਲਾਓ",
    "submitComplaint": "ਸ਼ਿਕਾਇਤ ਜਮ੍ਹਾਂ ਕਰੋ",
    "continue": "ਜਾਰੀ ਰੱਖੋ",
    "back": "ਪਿੱਛੇ",
    "securityCheck": "ਸੁਰੱਖਿਆ ਜਾਂਚ: 7 + 4 ਦਰਜ ਕਰੋ",
    "successRedirect": "ਤੁਹਾਡੀ ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰ ਲਈ ਗਈ ਹੈ। ਨਿਰਧਾਰਤ ਅਧਿਕਾਰੀ ਥਾਂ ਖੱਲੀ ਹੋ ਰਹੀ ਹੈ…",
    "openOfficial": "ਨਿਰਧਾਰਤ ਅਧਿਕਾਰੀ ਵੈਬਸਾਈਟ ਖੋਲ੍ਹੋ",
    "seeOfficer": "ਉਪਰ ਦਿੱਤੇ ਅਧਿਕਾਰੀ ਨੂੰ ਵੇਖੋ",
    "officialDestination": "ਸਹੀ ਅਧਿਕਾਰੀ ਗੰਢਵੰਤੀ ਚੁਣੋ",
    "education": "ਸਿੱਖਿਆ",
    "backPortal": "ਪੋਰਟਲ ਤੇ ਵਾਪਸ ਜਾਓ",
    "useGuide": "ਇਸਨੂੰ ਮਾਰਗਦਰਸ਼ਕ ਵਜੋਂ ਵਰਤੋਂ",
    "safetyReminder": "ਸੁਰੱਖਿਆ ਯਾਦ"
  },
  "sa": {
    "fullName": "पूर्ण नाम",
    "yourFullName": "भवतः पूर्ण नाम",
    "mobileNumber": "मोबाइल संख्या",
    "tenDigitMobile": "10-अङ्कीय मोबाइल",
    "emailOptional": "ईमेल (ऐच्छिक)",
    "emailPlaceholder": "you@example.com",
    "addressCityOptional": "पता / नगर (ऐच्छिक)",
    "whereAgenciesReach": "संस्थाः भवतः कुत्र प्राप्नुवन्ति",
    "idType": "परिचय प्रकारः",
    "voterId": "मतदाता परिचयपत्रम्",
    "pan": "PAN",
    "drivingLicence": "चालक अनुज्ञापत्रम्",
    "idNumber": "ID संख्या",
    "enterIdNumber": "ID संख्या प्रविश्यत",
    "oneTimePassword": "एकवारस्य कूटशब्दः",
    "otpPlaceholder": "6-अङ्कीय OTP",
    "sending": "प्रेष्यते…",
    "sendOtp": "OTP प्रेषयतु",
    "checking": "परीक्ष्यते…",
    "verifyOtp": "OTP प्रमाणीकरोतु",
    "phoneVerified": "दूरवाणी प्रमात्ता",
    "reportAnonymously": "अनामिकेन प्रतिवेदनं कुर्वन्तु",
    "noIdentityRequired": "नाम, दूरवाणी वा परिचयपत्रं न आवश्यकं। भवन्तः ट्रैकिंग ID लभ्यते।",
    "select": "चिन्तयतु",
    "whoAsked": "कः घूसम् अपेक्षते अथवा आहरत्?",
    "centralEmployee": "केन्द्रीय राष्‍ट्रीय कर्मकरः / PSU / बैंकः",
    "stateEmployee": "राज्य सरकारस्य वा स्थानिक संस्थायाः कर्मकरः",
    "policeVigilance": "पुलिस् वा निरीक्षणकर्मकरः",
    "onlineDemand": "ऑनलाइन / दूरवाणि / UPI याचना",
    "notSure": "निश्चितं न",
    "officialName": "अधिकारीनाम (यदि ज्ञायते)",
    "officialNamePlaceholder": "e.g. Ramesh Verma",
    "designation": "पदम्",
    "designationPlaceholder": "e.g. Clerk, Inspector",
    "departmentOffice": "विभागः / कार्यालयम्",
    "departmentPlaceholder": "e.g. Regional Passport Office",
    "officeAddress": "कार्यालयस्य ठिकाणम् / क्षेत्रम्",
    "officeAddressPlaceholder": "Building, street, city or district",
    "serviceWork": "कया सेवा वा कर्म समाविष्टम्?",
    "servicePlaceholder": "e.g. Building permit, licence renewal, pension file",
    "whatDemanded": "किम् अपेक्षितम्",
    "amountPaid": "अपेक्षितम्/प्रदत्तम् परिमाणम् (₹)",
    "amountPlaceholder": "e.g. 2000",
    "paymentForm": "प्रदानेन प्रकारः",
    "cash": "नगदम्",
    "upi": "UPI / ऑनलाइन स्थानान्तरणम्",
    "bankTransfer": "बैंक स्थानान्तरणम्",
    "giftGoods": "उपहारः वा वस्तूनि",
    "favourBenefit": "अनुकम्पा वा अन्य लाभः",
    "demandMaker": "कः याचितवान्?",
    "officialPersonally": "अधिकारी: स्वयम्",
    "intermediary": "मध्यस्थः / प्रतिनिधिः",
    "both": "उभे",
    "witnessDetails": "साक्षी/मध्यस्थ विवरणम्",
    "witnessPlaceholder": "नामानि च सम्पर्कः, यदि स्यात्",
    "dateDemand": "याचनायाः तिथिः",
    "timeApprox": "समयः (अनुमितः)",
    "placeDemand": "यत्र याचनां कृतवतः तत्र स्थानम्",
    "placePlaceholder": "e.g. Counter 4, office gate, over phone",
    "factsLabel": "अधिकारी किं उक्तवान् वा कृतवान् (केवल तथ्याणि)",
    "factsPlaceholder": "विस्तरेण यथार्थं किं उक्तं वा कृतं, क्रमशः वण्‍णयतु।",
    "evidenceLabel": "साक्ष्यं च संदर्भ विवरणम्",
    "evidencePlaceholder": "संदेशाः, दूरवाणी सङ्ख्या, ईमेल्, सूचनाः, पाणिभूतपत्तेः, स्क्रीनशॉट् अथवा व्यवहारविवरणम्",
    "referenceLabel": "आवेदनम् / फाइल् / अनुज्ञापत्र संदर्भ क्रमांकः",
    "referencePlaceholder": "e.g. Application No. 12345/2026",
    "finalReview": "अन्तिम समीकृति",
    "analysing": "विश्लेष्यते…",
    "exactWebsite": "नियतां वेबसाइटं अन्वेष्टुम्",
    "runAssistant": "प्रेषणात् पूर्वं AI सहायकञ्च सञ्चालयतु",
    "submitComplaint": "अपिचार्यम् समर्पयतु",
    "continue": "अग्रे यान्तु",
    "back": "पश्चात्",
    "securityCheck": "सुरक्षा परीक्षाः: 7 + 4 प्रविश्यत",
    "successRedirect": "भवतः अपिचार्यं अभिलेखीकृतम्। नियतं अधिकृत् गन्तव्यं उद्घाट्यते…",
    "openOfficial": "नियतां अधिकृत् वेबसाइट् उद्घाटयतु",
    "seeOfficer": "उपरितलिल अधिकारी पश्यतु",
    "officialDestination": "युक्तम् अधिकृत् गन्तव्यं चयनयतु",
    "education": "शिक्षा",
    "backPortal": "पोर्टलम् प्रत्यागच्छ",
    "useGuide": "एतत् मार्गदर्शिकायाः रूपेण उपयोक्तु",
    "safetyReminder": "सुरक्षा स्मरणम्"
  },
  "sat": {
    "fullName": "Full name",
    "yourFullName": "Your full name",
    "mobileNumber": "Mobile number",
    "tenDigitMobile": "10-digit mobile",
    "emailOptional": "Email (optional)",
    "emailPlaceholder": "you@example.com",
    "addressCityOptional": "Address / city (optional)",
    "whereAgenciesReach": "Where agencies can reach you",
    "idType": "ID type",
    "voterId": "Voter ID",
    "pan": "PAN",
    "drivingLicence": "Driving licence",
    "idNumber": "ID number",
    "enterIdNumber": "Enter ID number",
    "oneTimePassword": "One-time password",
    "otpPlaceholder": "6-digit OTP",
    "sending": "Sending…",
    "sendOtp": "Send OTP",
    "checking": "Checking…",
    "verifyOtp": "Verify OTP",
    "phoneVerified": "Phone verified",
    "reportAnonymously": "Report anonymously",
    "noIdentityRequired": "No name, phone, or ID required. You will receive a tracking ID.",
    "select": "Select",
    "whoAsked": "Who asked for or took the bribe?",
    "centralEmployee": "Central government employee / PSU / bank",
    "stateEmployee": "State government or local body employee",
    "policeVigilance": "Police or vigilance personnel",
    "onlineDemand": "Online / phone / UPI demand",
    "notSure": "Not sure",
    "officialName": "Official's name (if known)",
    "officialNamePlaceholder": "e.g. Ramesh Verma",
    "designation": "Designation",
    "designationPlaceholder": "e.g. Clerk, Inspector",
    "departmentOffice": "Department / office",
    "departmentPlaceholder": "e.g. Regional Passport Office",
    "officeAddress": "Office address / area",
    "officeAddressPlaceholder": "Building, street, city or district",
    "serviceWork": "What service or work was involved?",
    "servicePlaceholder": "e.g. Building permit, licence renewal, pension file",
    "whatDemanded": "What was demanded",
    "amountPaid": "Amount demanded / paid (₹)",
    "amountPlaceholder": "e.g. 2000",
    "paymentForm": "Form of payment",
    "cash": "Cash",
    "upi": "UPI / online transfer",
    "bankTransfer": "Bank transfer",
    "giftGoods": "Gift or goods",
    "favourBenefit": "Favour or other benefit",
    "demandMaker": "Who made the demand?",
    "officialPersonally": "The official personally",
    "intermediary": "An intermediary / agent / middleman",
    "both": "Both",
    "witnessDetails": "Witnesses / intermediary details",
    "witnessPlaceholder": "Names and contact, if any",
    "dateDemand": "Date of demand",
    "timeApprox": "Time (approx.)",
    "placeDemand": "Place where the demand was made",
    "placePlaceholder": "e.g. Counter 4, office gate, over phone",
    "factsLabel": "What the official said or did (facts only)",
    "factsPlaceholder": "Describe exactly what was said or done, in order.",
    "evidenceLabel": "Evidence and reference details",
    "evidencePlaceholder": "Messages, phone numbers, emails, notices, receipts, screenshots or transaction details",
    "referenceLabel": "Application / file / licence reference number",
    "referencePlaceholder": "e.g. Application No. 12345/2026",
    "finalReview": "Final review",
    "analysing": "Analysing…",
    "exactWebsite": "Find exact website",
    "runAssistant": "Run the AI assistant before submitting",
    "submitComplaint": "Submit complaint",
    "continue": "Continue",
    "back": "Back",
    "securityCheck": "Security check: enter 7 + 4",
    "successRedirect": "Your complaint was recorded. Opening the exact official destination…",
    "openOfficial": "Open exact official website",
    "seeOfficer": "See officer above",
    "officialDestination": "Choose the correct official destination",
    "education": "Education",
    "backPortal": "Back to portal",
    "useGuide": "Use this as a guide",
    "safetyReminder": "Safety reminder"
  },
  "sd": {
    "fullName": "پورو نالو",
    "yourFullName": "توهانجو پورو نالو",
    "mobileNumber": "موبائل نمبر",
    "tenDigitMobile": "10-عدد موبائل",
    "emailOptional": "اِي ميل (اختياري)",
    "emailPlaceholder": "you@example.com",
    "addressCityOptional": "پتو / شهر (اختياري)",
    "whereAgenciesReach": "ڪٿي ايجنسيون توهان تائين پهچي سگهن ٿيون",
    "idType": "شناخت جو قسم",
    "voterId": "وٽر آءِ ڊي",
    "pan": "PAN",
    "drivingLicence": "ڊرائيونگ لائسنس",
    "idNumber": "شناخت نمبر",
    "enterIdNumber": "شناخت نمبر داخل ڪريو",
    "oneTimePassword": "هڪ دفعو پاسورڊ",
    "otpPlaceholder": "6-عددي OTP",
    "sending": "موڪلي رهيو آهي…",
    "sendOtp": "OTP موڪليو",
    "checking": "چيڪ پيو ٿئي…",
    "verifyOtp": "OTP جي تصديق ڪريو",
    "phoneVerified": "فون جي تصديق ٿي وئي",
    "reportAnonymously": "گمنام رپورٽ ڪريو",
    "noIdentityRequired": "نالو، فون يا آءِ ڊي گهربل ناهي. توھان کي ٽريڪنگ ID موڪلي ويندي.",
    "select": "منتخب ڪريو",
    "whoAsked": "رشوت لاءَ ڪنهن گهر ڪيو يا ورتو؟",
    "centralEmployee": "مرڪزي حڪومت جو ملازم / PSU / بئنڪ",
    "stateEmployee": "رياستي حڪومت يا مقامي ادارو ملازم",
    "policeVigilance": "پوليس يا ويجيليَنس عملي",
    "onlineDemand": "آن لائن / فون / UPI گهر",
    "notSure": "يقين نه آهي",
    "officialName": "آفيسر جو نالو (جيڪڏهن معلوم هجي)",
    "officialNamePlaceholder": "مثال: Ramesh Verma",
    "designation": "عهدو",
    "designationPlaceholder": "مثال: ڪلارڪ، انسپيڪٽر",
    "departmentOffice": "ڊپارٽمينٽ / آفيس",
    "departmentPlaceholder": "مثال: Regional Passport Office",
    "officeAddress": "آفيس جو پتو / علائقو",
    "officeAddressPlaceholder": "بلڊنگ، گهٽي، شهر يا ضلعي",
    "serviceWork": "ڪهڙي سهولت يا ڪم سان تعلق رکي ٿو؟",
    "servicePlaceholder": "مثال: Building permit, licence renewal, pension file",
    "whatDemanded": "ڇا گهريو ويو",
    "amountPaid": "گهرائي وئي / ادا ڪيل رقم (₹)",
    "amountPlaceholder": "مثال: 2000",
    "paymentForm": "ادائيگي جو طريقو",
    "cash": "نقد",
    "upi": "UPI / آن لائن ٽرانسفر",
    "bankTransfer": "بينڪ ٽرانسفر",
    "giftGoods": "تحفو يا سامان",
    "favourBenefit": "سہولت يا ٻيو فائدو",
    "demandMaker": "گهر ڪنهن ڪيو؟",
    "officialPersonally": "آفيسر پاڻ",
    "intermediary": "واسطيدار / ايجنٽ / وچولو",
    "both": "ٻئي",
    "witnessDetails": "گواهن / واسطيدار جا تفصيل",
    "witnessPlaceholder": "نالا ۽ رابطو، جيڪڏهن ڪجھ هجي",
    "dateDemand": "گهر جي تاريخ",
    "timeApprox": "وقت (تقريباً)",
    "placeDemand": "جڳھ جتي گهر ڪيو ويو",
    "placePlaceholder": "مثال: Counter 4, office gate, over phone",
    "factsLabel": "آفيسر ڇا چيو يا ڪيو (صرف حقيقتون)",
    "factsPlaceholder": "عین مطابق بيان ڪريو ڇا چيو يا ڪيو ويو، ترتيب سان.",
    "evidenceLabel": "ثبوت ۽ حوالا جا تفصيل",
    "evidencePlaceholder": "ميسيجز، فون نمبر، اي ميلون، نوٽيس، رسيدون، اسڪرين شاٽ يا ٽرانزيڪشن جا تفصيل",
    "referenceLabel": "درخواست / فائل / لائسنس حوالو نمبر",
    "referencePlaceholder": "مثال: Application No. 12345/2026",
    "finalReview": "حتمي جائزو",
    "analysing": "جائزو پيو ورتو وڃي…",
    "exactWebsite": "صحیح ويب سائيٽ ڳولهيو",
    "runAssistant": "جمع ڪرڻ کان اڳ AI اسسٽنٽ هلائو",
    "submitComplaint": "شڪايت جمع ڪريو",
    "continue": "جاري رکو",
    "back": "واپس",
    "securityCheck": "سڪيورٽي چيڪ: 7 + 4 داخل ڪريو",
    "successRedirect": "توهان جي شڪايت ريڪارڊ ٿي وئي. صحيح سرڪاري منزل کولڻ…",
    "openOfficial": "صحیح سرڪاري ويب سائيٽ کوليو",
    "seeOfficer": "مٿي آفيسر ڏسو",
    "officialDestination": "صحیح سرڪاري منزل چونڊيو",
    "education": "تعليم",
    "backPortal": "پورٽل تي واپس",
    "useGuide": "هن کي هڪ راهنمائي طور استعمال ڪريو",
    "safetyReminder": "حفاظتي ياد ڏياريندڙ"
  },
  "ta": {
    "fullName": "முழு பெயர்",
    "yourFullName": "உங்கள் முழு பெயர்",
    "mobileNumber": "மொபைல் எண்",
    "tenDigitMobile": "10-இலக்க தொலைபேசி",
    "emailOptional": "மின்னஞ்சல் (விரும்பினால்)",
    "emailPlaceholder": "you@example.com",
    "addressCityOptional": "முகவரி / நகரம் (விரும்பினால்)",
    "whereAgenciesReach": "ஏஜென்சிகள் எங்கு sizi அணியலாம்",
    "idType": "அடையாள வகை",
    "voterId": "வாக்காளர் ஐடி",
    "pan": "PAN",
    "drivingLicence": "ஓட்டுனர் உரிமம்",
    "idNumber": "அடையாள எண்",
    "enterIdNumber": "அடையாள எண் உள்ளிடவும்",
    "oneTimePassword": "ஒருமுறை கடவுச்சொல்",
    "otpPlaceholder": "6-இலக்க OTP",
    "sending": "அனுப்பப்படுகிறது…",
    "sendOtp": "OTP அனுப்பு",
    "checking": "சரிபார்க்கப்படுகிறது…",
    "verifyOtp": "OTP ஐ சரிபார்க்கவும்",
    "phoneVerified": "தொலைபேசி சரிபடியப்பட்டுள்ளது",
    "reportAnonymously": "பெயரற்ற முறையில் தகவல் அளிக்க",
    "noIdentityRequired": "பெயர், தொலைபேசி அல்லது அடையாளம் தேவையில்லை. உங்களுக்கு ஒரு டிராக்கிங் ஐடி வழங்கப்படும்.",
    "select": "தேர்வு செய்க",
    "whoAsked": "பணம் கோரியது அல்லது எடுத்தது யார்?",
    "centralEmployee": "மத்திய அரசு ஊழியர் / PSU / வங்கி",
    "stateEmployee": "மாநில அரசு அல்லது உள்ளூர் அமைப்பின் ஊழியர்",
    "policeVigilance": "போலீசு அல்லது வயலன்ஸ் பணியாளர்",
    "onlineDemand": "ஆன்லைன் / தொலைபேசி / UPI கோரிக்கை",
    "notSure": "தன்மோசமில்லை",
    "officialName": "அதிகாரியின் பெயர் (அறிந்திருந்தால்)",
    "officialNamePlaceholder": "உதா: Ramesh Verma",
    "designation": "பதவி",
    "designationPlaceholder": "உதா: கிளார்க், இன்ஸ்பெக்டர்",
    "departmentOffice": "துறை / அலுவலகம்",
    "departmentPlaceholder": "உதா: Regional Passport Office",
    "officeAddress": "அலுவலக முகவரி / பகுதி",
    "officeAddressPlaceholder": "கட்டிடம், தெரு, நகரம் அல்லது மாவட்டம்",
    "serviceWork": "எந்த சேவை அல்லது வேலை தொடர்பானது?",
    "servicePlaceholder": "உதா: Building permit, licence renewal, pension file",
    "whatDemanded": "என்ன கோரப்பட்டது",
    "amountPaid": "கோரப்பட்ட/செலுத்தப்பட்ட தொகை (₹)",
    "amountPlaceholder": "உதா: 2000",
    "paymentForm": "கட்டண வடிவம்",
    "cash": "நகடு",
    "upi": "UPI / ஆன்லைன் மாற்றம்",
    "bankTransfer": "வங்கி பரிமாற்றம்",
    "giftGoods": "பரிசு அல்லது பொருட்கள்",
    "favourBenefit": "நன்மை அல்லது பிற நன்மை",
    "demandMaker": "கோரிக்கையை யார் செய்தார்?",
    "officialPersonally": "அதிகாரி தனிப்பட்ட முறையில்",
    "intermediary": "ஒப்பந்தகர் / முகவர் / நடுவண்",
    "both": "இரண்டும்",
    "witnessDetails": "சாட்சிகள் / நடுவணின் விவரங்கள்",
    "witnessPlaceholder": "பெயர்கள் மற்றும் தொடர்பு, இருந்தால்",
    "dateDemand": "கோரிக்கை தேதி",
    "timeApprox": "நேரம் (எண்ணிக்கையாக)",
    "placeDemand": "கோரிக்கை செய்யப்பட்ட இடம்",
    "placePlaceholder": "உதா: Counter 4, office gate, over phone",
    "factsLabel": "அதிகாரி என்ன சொன்னார் அல்லது செய்தார் (உண்மைகள் மட்டும்)",
    "factsPlaceholder": "சொன்னது அல்லது செய்ததை துல்லியமாக, வரிசையாக விவரிக்கவும்.",
    "evidenceLabel": "சாட்சி மற்றும் குறிப்புகள் விவரங்கள்",
    "evidencePlaceholder": "செய்திகள், தொலைபேசி எண்கள், மின்னஞ்சல்கள், அறிவிப்புகள், ரசீது, ஸ்கிரீன் ஷாட் அல்லது பரிவர்த்தனை விவரங்கள்",
    "referenceLabel": "விண்ணப்பம் / கோப்பு / உரிமத்தின் குறிப்பு எண்",
    "referencePlaceholder": "உதா: Application No. 12345/2026",
    "finalReview": "இறுதி பரிசீலனை",
    "analysing": "பகுப்பாய்வு…",
    "exactWebsite": "சரியான வலைத்தளத்தை கண்டறியவும்",
    "runAssistant": "சமர்ப்பிப்பதற்கு முன் AI உதவியை இயக்கவும்",
    "submitComplaint": "புகாரை சமர்ப்பிக்கவும்",
    "continue": "தொடரவும்",
    "back": "வீடு",
    "securityCheck": "பாதுகாப்பு சோதனை: 7 + 4 உள்ளிடவும்",
    "successRedirect": "உங்கள் புகார் பதிவுசெய்யப்பட்டது. சரியான அதிகாரப் பக்கம் திறக்கப்படுகிறது…",
    "openOfficial": "சரியான அதிகாரப்பூர்வ வலைத்தளத்தைத் திறக்கவும்",
    "seeOfficer": "மேலுள்ள அதிகாரியைக் காட்டு",
    "officialDestination": "சரியான அதிகாரப் பயணத்தை தேர்ந்தெடுக்கவும்",
    "education": "கல்வி",
    "backPortal": "போர்டலுக்கு திரும்பவும்",
    "useGuide": "இதை வழிகாட்டியாக பயன்படுத்தவும்",
    "safetyReminder": "பாதுகாப்பு எச்சரிக்கை"
  },
  "te": {
    "fullName": "పూర్తి పేరు",
    "yourFullName": "మీ పూర్తి పేరు",
    "mobileNumber": "మొబైల్ నంబర్",
    "tenDigitMobile": "10-అంకెల మొబైల్",
    "emailOptional": "ఇమెయిల్ (ఐచ్ఛికం)",
    "emailPlaceholder": "you@example.com",
    "addressCityOptional": "చిరునామా / నగరం (ఐచ్ఛికం)",
    "whereAgenciesReach": "ఏజెన్సీలు మీరు ఎక్కడ చేరగలవు",
    "idType": "ID రకం",
    "voterId": "వోటర్ ID",
    "pan": "PAN",
    "drivingLicence": "డ్రైవింగ్ లైసెన్స్",
    "idNumber": "ఐడి నంబర్",
    "enterIdNumber": "ఐడి నంబర్ నమోదు చేయండి",
    "oneTimePassword": "ఒకసారి పాస్‌వర్డ్",
    "otpPlaceholder": "6-అంకెల OTP",
    "sending": "పంపుతోంది…",
    "sendOtp": "OTP పంపండి",
    "checking": "పరిశీలిస్తున్నారు…",
    "verifyOtp": "OTP నిర్ధారించండి",
    "phoneVerified": "ఫోన్ నిర్ధారించబడింది",
    "reportAnonymously": "పేర్లేని రీతిలో నివేదిక ఇవ్వండి",
    "noIdentityRequired": "పేరు, ఫోన్, లేదా ID అవసరం లేదు. మీకు ట్రాకింగ్ ID అందుతుంది.",
    "select": "ఎంచుకోండి",
    "whoAsked": "లంచం కోరిన లేదా తీసుకున్న వారు ఎవరు?",
    "centralEmployee": "కేంద్ర ప్రభుత్వం ఉద్యోగి / PSU / బ్యాంక్",
    "stateEmployee": "రాష్ట్ర ప్రభుత్వం లేదా స్థానిక సంస్థ ఉద్యోగి",
    "policeVigilance": "పోలీసు లేదా వివేళెన్స్ సిబ్బంది",
    "onlineDemand": "ఆన్లైన్ / ఫోన్ / UPI డిమాండ్",
    "notSure": "నिश्चितంగా లేదు",
    "officialName": "అధికారి పేరు (తెలిస్తుంటే)",
    "officialNamePlaceholder": "ఉదా: Ramesh Verma",
    "designation": "హోదా",
    "designationPlaceholder": "ఉదా: క్లర్క్, ఇన్‌స్పెక్టర్",
    "departmentOffice": "విభాగం / కార్యాలయం",
    "departmentPlaceholder": "ఉదా: Regional Passport Office",
    "officeAddress": "కార్యాలయ చిరునామా / ప్రాంతం",
    "officeAddressPlaceholder": "బిల్డింగ్, వీధి, నగరం లేదా జిల్లా",
    "serviceWork": "ఏ సేవ లేదా పని సంబంధించింది?",
    "servicePlaceholder": "ఉదా: Building permit, licence renewal, pension file",
    "whatDemanded": "ఏం కోరారు",
    "amountPaid": "కోరిన/చెల్లించిన మొత్తం (₹)",
    "amountPlaceholder": "ఉదా: 2000",
    "paymentForm": "చెల్లింపు రూపం",
    "cash": "నగదు",
    "upi": "UPI / ఆన్‌లైన్ ట్రాన్స్‌ఫర్",
    "bankTransfer": "బ్యాంక్ ట్రాన్స్‌ఫర్",
    "giftGoods": "బహుమతి లేదా వస్తువులు",
    "favourBenefit": "ప్రీతి లేదా ఇతర లాభం",
    "demandMaker": "డిమాండ్ ఎవరు చేశారు?",
    "officialPersonally": "అధికారి వ్యక్తిగతంగా",
    "intermediary": "మధ్యవర్తి / ఏజెంట్ / మధ్యస్తుడు",
    "both": "రెండూ",
    "witnessDetails": "సాక్షుల / మధ్యవర్తుల వివరాలు",
    "witnessPlaceholder": "పేర్లు మరియు సంప్రదింపు, ఎ varsa",
    "dateDemand": "డిమాండ్ తేదీ",
    "timeApprox": "సమయం (సుమారు)",
    "placeDemand": "డిమాండ్ జరిగిన స్థలం",
    "placePlaceholder": "ఉదా: Counter 4, office gate, over phone",
    "factsLabel": "అధికారీ చెప్పినది లేదా చేసినది (కేవలం వాస్తవాలు)",
    "factsPlaceholder": "ఏం చెప్పారో లేదా చేశారో క్రమంగా ఖచ్చితంగా వర్ణించండి.",
    "evidenceLabel": "ప్రూఫ్ మరియు రిఫరెన్స్ వివరాలు",
    "evidencePlaceholder": "మెసేజ్‌లు, ఫోన్ నంబర్లు, ఇమెయిల్స్, నోటీసులు, రసీదులు, స్క్రీన్ షాట్లు లేదా లావాదేవీ వివరాలు",
    "referenceLabel": "అప్లికేషన్ / ఫైల్ / లైసెన్స్ సూచనలు సంఖ్య",
    "referencePlaceholder": "ఉదా: Application No. 12345/2026",
    "finalReview": "అంతిమ సమీక్ష",
    "analysing": "విశ్లేషణ చేస్తున్నారు…",
    "exactWebsite": "నిశిత వెబ్‌సైట్ కనుగొనండి",
    "runAssistant": "సమర్పించే ముందు AI సహాయకుడిని నడపండి",
    "submitComplaint": "ఫిర్యాదు సమర్పించండి",
    "continue": "కొనసాగించండి",
    "back": "వెనుకకు",
    "securityCheck": "భద్రతా తనిఖీ: 7 + 4 నమోదు చేయండి",
    "successRedirect": "మీ ఫిర్యాదు నమోదు చేయబడింది. సరైన అధికారిక గమ్యస్థానాన్ని తెరవటం…",
    "openOfficial": "సరైన అధికారిక వెబ్‌సైట్ తెరవండి",
    "seeOfficer": "పైన అధికారిని చూడండి",
    "officialDestination": "صحیح అధికారిక గమ్యస్థానాన్ని ఎంచుకోండి",
    "education": "విద్య",
    "backPortal": "పోర్టల్‌కి తిరుగు",
    "useGuide": "దీనిని మార్గదర్శకంగా ఉపయోగించండి",
    "safetyReminder": "భద్రత జ్ఞాపకం"
  },
  "ur": {
    "fullName": "پورا نام",
    "yourFullName": "آپ کا پورا نام",
    "mobileNumber": "موبائل نمبر",
    "tenDigitMobile": "10-ہندسہ موبائل",
    "emailOptional": "ای میل (اختیاری)",
    "emailPlaceholder": "you@example.com",
    "addressCityOptional": "پتہ / شہر (اختیاری)",
    "whereAgenciesReach": "ادارے آپ تک کہاں پہنچ سکتے ہیں",
    "idType": "شناخت کی قسم",
    "voterId": "ووٹر شناختی کارڈ",
    "pan": "PAN",
    "drivingLicence": "ڈرائیونگ لائسنس",
    "idNumber": "شناختی نمبر",
    "enterIdNumber": "شناختی نمبر درج کریں",
    "oneTimePassword": "ایک وقتی پاس ورڈ",
    "otpPlaceholder": "6-ہندسوں والا OTP",
    "sending": "بھیجا جا رہا ہے…",
    "sendOtp": "OTP بھیجیں",
    "checking": "چیک کیا جا رہا ہے…",
    "verifyOtp": "OTP کی تصدیق کریں",
    "phoneVerified": "فون تصدیق شدہ",
    "reportAnonymously": "گمنام طور پر رپورٹ کریں",
    "noIdentityRequired": "نام، فون، یا شناختی کارڈ درکار نہیں۔ آپ کو ایک ٹریکنگ ID موصول ہوگی۔",
    "select": "منتخب کریں",
    "whoAsked": "رشوت کس نے مانگی یا لی؟",
    "centralEmployee": "مرکزی حکومت کا ملازم / PSU / بینک",
    "stateEmployee": "ریاستی حکومت یا مقامی ادارے کا ملازم",
    "policeVigilance": "پولیس یا نگرانی عملہ",
    "onlineDemand": "آن لائن / فون / UPI کی مانگ",
    "notSure": "یقین نہیں",
    "officialName": "افسر کا نام (اگر معلوم ہو)",
    "officialNamePlaceholder": "مثال: Ramesh Verma",
    "designation": "عہدہ",
    "designationPlaceholder": "مثال: کلرک، انسپکٹر",
    "departmentOffice": "محکمہ / دفتر",
    "departmentPlaceholder": "مثال: Regional Passport Office",
    "officeAddress": "دفتر کا پتہ / علاقہ",
    "officeAddressPlaceholder": "بلڈنگ، سڑک، شہر یا ضلع",
    "serviceWork": "کون سی سروس یا کام شامل تھا؟",
    "servicePlaceholder": "مثال: Building permit, licence renewal, pension file",
    "whatDemanded": "کیا مانگا گیا",
    "amountPaid": "مانگی گئی/ادا کی گئی رقم (₹)",
    "amountPlaceholder": "مثال: 2000",
    "paymentForm": "ادائیگی کی شکل",
    "cash": "نقد",
    "upi": "UPI / آن لائن ٹرانسفر",
    "bankTransfer": "بینک ٹرانسفر",
    "giftGoods": "تحفہ یا سامان",
    "favourBenefit": "رعأیت یا دیگر فائدہ",
    "demandMaker": "مطالبہ کس نے کیا؟",
    "officialPersonally": "افسر خود ذاتی طور پر",
    "intermediary": "درمیان کار / ایجنٹ / ثالث",
    "both": "دونوں",
    "witnessDetails": "گواہوں / درمیان کار کی تفصیلات",
    "witnessPlaceholder": "نام اور رابطہ، اگر کوئی ہوں",
    "dateDemand": "مطالبہ کی تاریخ",
    "timeApprox": "وقت (تقریباً)",
    "placeDemand": "جگہ جہاں مطالبہ کیا گیا",
    "placePlaceholder": "مثال: Counter 4, office gate, over phone",
    "factsLabel": "افسر نے کیا کہا یا کیا (صرف حقائق)",
    "factsPlaceholder": "بالکل بیان کریں کہ کیا کہا یا کیا گیا، ترتیب کے ساتھ.",
    "evidenceLabel": "ثبوت اور حوالہ کی تفصیلات",
    "evidencePlaceholder": "پیغامات، فون نمبر، ای میلز، نوٹس، رسیدیں، اسکرین شاٹس یا ٹرانزیکشن کی تفصیلات",
    "referenceLabel": "درخواست / فائل / لائسنس حوالہ نمبر",
    "referencePlaceholder": "مثال: Application No. 12345/2026",
    "finalReview": "حتمی جائزہ",
    "analysing": "تجزیہ کیا جا رہا ہے…",
    "exactWebsite": "درست ویب سائٹ تلاش کریں",
    "runAssistant": "جمع کروانے سے پہلے AI اسسٹنٹ چلائیں",
    "submitComplaint": "شکایت جمع کریں",
    "continue": "جاری رکھیں",
    "back": "پیچھے",
    "securityCheck": "سیکورٹی چیک: 7 + 4 درج کریں",
    "successRedirect": "آپ کی شکایت درج کر لی گئی ہے۔ درست سرکاری مقام کھول رہا ہے…",
    "openOfficial": "درست سرکاری ویب سائٹ کھولیں",
    "seeOfficer": "اوپر افسر دیکھیں",
    "officialDestination": "صحیح سرکاری مقام منتخب کریں",
    "education": "تعلیم",
    "backPortal": "پورٹل پر واپس",
    "useGuide": "اسے رہنما کے طور پر استعمال کریں",
    "safetyReminder": "حفاظتی یاددہانی"
  }
} as const;
