export type AgencyRecord = {
  level: string;
  stateOrUt: string;
  bodyName: string;
  type: string;
  jurisdiction: string;
  functions: string;
  officialWebsite: string;
  helpline: string;
  email: string;
  address: string;
};

export const AGENCY_DIRECTORY: AgencyRecord[] = [
  {
    "level": "National",
    "stateOrUt": "India",
    "bodyName": "Lokpal of India",
    "type": "Ombudsman",
    "jurisdiction": "PM (with exclusions), Union Ministers, MPs, Group A-D central officials, Centre-funded bodies",
    "functions": "Anti-corruption investigation; can supervise CBI; recommend prosecution; issue guidelines",
    "officialWebsite": "https://lokpalonline.gov.in/",
    "helpline": "Direct filing via portal",
    "email": "Via portal",
    "address": "New Delhi"
  },
  {
    "level": "National",
    "stateOrUt": "India",
    "bodyName": "Central Vigilance Commission (CVC)",
    "type": "Vigilance Commission",
    "jurisdiction": "Central govt departments, PSUs, public sector banks, insurance companies",
    "functions": "Receives complaints & whistleblower disclosures; sends to concerned CVO for investigation",
    "officialWebsite": "https://portal.cvc.gov.in/",
    "helpline": "1800-11-0180",
    "email": "Via portal",
    "address": "Satarkta Bhavan, Block-A, GPO Complex, INA, New Delhi-110023"
  },
  {
    "level": "National",
    "stateOrUt": "India",
    "bodyName": "Central Bureau of Investigation (CBI)",
    "type": "Police Agency",
    "jurisdiction": "Central govt staff, PSUs, central banks (investigations under PC Act)",
    "functions": "Investigates corruption, bribery, trap cases, disproportionate assets",
    "officialWebsite": "https://cbi.gov.in/",
    "helpline": "011-24367887",
    "email": "hobacdel@cbi.gov.in",
    "address": "CGO Complex, Lodhi Road, New Delhi-110003"
  },
  {
    "level": "National",
    "stateOrUt": "India",
    "bodyName": "Enforcement Directorate (ED)",
    "type": "Law Enforcement",
    "jurisdiction": "All India (PMLA & FEMA violations)",
    "functions": "Money laundering enforcement; proceeds of corruption",
    "officialWebsite": "https://enforcementdirectorate.gov.in/",
    "helpline": "Contact regional offices",
    "email": "Via website",
    "address": "New Delhi"
  },
  {
    "level": "National",
    "stateOrUt": "India",
    "bodyName": "CPGRAMS (Centralized Public Grievance System)",
    "type": "Grievance Portal",
    "jurisdiction": "All types of grievances including corruption",
    "functions": "Routes complaints to concerned department; tracks status",
    "officialWebsite": "https://pgportal.gov.in/",
    "helpline": "Online portal",
    "email": "Via portal",
    "address": "Available nationwide"
  },
  {
    "level": "State",
    "stateOrUt": "Andhra Pradesh",
    "bodyName": "A.P. Lokayukta",
    "type": "Ombudsman",
    "jurisdiction": "State officials, ministers, legislators, local bodies (est. 1983)",
    "functions": "Inquiries into corruption & maladministration",
    "officialWebsite": "https://www.lokayukta.ap.gov.in/",
    "helpline": "08518-267268",
    "email": "ap.Lokayukta@gmail.com",
    "address": "Kurnool"
  },
  {
    "level": "State",
    "stateOrUt": "Arunachal Pradesh",
    "bodyName": "State Vigilance & Lokayukta",
    "type": "Vigilance/Ombudsman",
    "jurisdiction": "State government staff & officials",
    "functions": "Anti-corruption investigations",
    "officialWebsite": "Portal not confirmed",
    "helpline": "1064 (state helpline)",
    "email": "Via CPGRAMS",
    "address": "Itanagar"
  },
  {
    "level": "State",
    "stateOrUt": "Assam",
    "bodyName": "Directorate of Vigilance & Anti-Corruption & Assam Lokayukta",
    "type": "ACB + Ombudsman",
    "jurisdiction": "State officials, local bodies, state PSUs",
    "functions": "Vigilance investigations & ombudsman inquiries",
    "officialWebsite": "dvac.assam.gov.in",
    "helpline": "1064",
    "email": "Via website",
    "address": "Guwahati"
  },
  {
    "level": "State",
    "stateOrUt": "Bihar",
    "bodyName": "Vigilance Investigation Bureau & Bihar Lokayukta",
    "type": "Vigilance + Ombudsman",
    "jurisdiction": "State government officials & public servants",
    "functions": "Corruption investigations & maladministration inquiries",
    "officialWebsite": "vigilance.bihar.gov.in",
    "helpline": "1064",
    "email": "Via website",
    "address": "Patna"
  },
  {
    "level": "State",
    "stateOrUt": "Chhattisgarh",
    "bodyName": "ACB & Economic Offences Wing (EOW)",
    "type": "Police Agency",
    "jurisdiction": "State govt, local bodies, state PSUs, officials",
    "functions": "Trap cases, corruption & economic offence investigations",
    "officialWebsite": "https://acbeow.cg.gov.in/",
    "helpline": "1064 / 8827461064 (WhatsApp)",
    "email": "compaintacbeow@gmail.com",
    "address": "Raipur"
  },
  {
    "level": "State",
    "stateOrUt": "Goa",
    "bodyName": "Goa Vigilance & Anti-Corruption Bureau & Goa Lokayukta",
    "type": "ACB + Ombudsman",
    "jurisdiction": "State officials & public servants",
    "functions": "Vigilance & ombudsman functions",
    "officialWebsite": "Portal not confirmed",
    "helpline": "1064",
    "email": "Via CPGRAMS",
    "address": "Panaji"
  },
  {
    "level": "State",
    "stateOrUt": "Gujarat",
    "bodyName": "Anti-Corruption Bureau & Gujarat Lokayukta",
    "type": "ACB + Ombudsman",
    "jurisdiction": "State officials, local bodies, PSUs",
    "functions": "Trap cases, investigations, ombudsman inquiries",
    "officialWebsite": "https://lokayukta.gujarat.gov.in/ & https://acb.gujarat.gov.in/",
    "helpline": "1064",
    "email": "arlok@gujarat.gov.in",
    "address": "Gandhinagar"
  },
  {
    "level": "State",
    "stateOrUt": "Haryana",
    "bodyName": "Anti-Corruption Bureau & Haryana Lokayukta",
    "type": "ACB + Ombudsman",
    "jurisdiction": "State officials & public servants",
    "functions": "Corruption investigations & maladministration inquiries",
    "officialWebsite": "Portal not confirmed",
    "helpline": "1064 / 1800-180-2022",
    "email": "Via website",
    "address": "Chandigarh"
  },
  {
    "level": "State",
    "stateOrUt": "Himachal Pradesh",
    "bodyName": "Vigilance & Anti-Corruption Bureau & HP Lokayukta",
    "type": "Vigilance + Ombudsman",
    "jurisdiction": "State officials & public servants",
    "functions": "Vigilance & ombudsman functions",
    "officialWebsite": "Portal not confirmed",
    "helpline": "1064",
    "email": "Via CPGRAMS",
    "address": "Shimla"
  },
  {
    "level": "State",
    "stateOrUt": "Jharkhand",
    "bodyName": "Anti-Corruption Bureau & Jharkhand Lokayukta",
    "type": "ACB + Ombudsman",
    "jurisdiction": "State govt officials, local bodies, PSUs",
    "functions": "Corruption investigations & ombudsman inquiries",
    "officialWebsite": "https://acb.jharkhand.gov.in/",
    "helpline": "1064",
    "email": "Via website",
    "address": "Ranchi"
  },
  {
    "level": "State",
    "stateOrUt": "Karnataka",
    "bodyName": "Lokayukta (with Police Wing)",
    "type": "Ombudsman with Police",
    "jurisdiction": "State officials, local bodies, PSUs (ACB dissolved 2022)",
    "functions": "Corruption investigations, ombudsman inquiries, trap cases",
    "officialWebsite": "https://lokayukta.karnataka.gov.in/",
    "helpline": "1064",
    "email": "Via website",
    "address": "Bengaluru"
  },
  {
    "level": "State",
    "stateOrUt": "Kerala",
    "bodyName": "Vigilance & Anti-Corruption Bureau & Kerala Lokayukta",
    "type": "Vigilance + Ombudsman",
    "jurisdiction": "State officials & public servants",
    "functions": "Corruption investigations & ombudsman functions",
    "officialWebsite": "https://vigilance.kerala.gov.in/",
    "helpline": "1064",
    "email": "Via website",
    "address": "Thiruvananthapuram"
  },
  {
    "level": "State",
    "stateOrUt": "Madhya Pradesh",
    "bodyName": "Special Police Establishment (SPE) & EOW; MP Lokayukta",
    "type": "Police + Ombudsman",
    "jurisdiction": "State officials, local bodies, PSUs (SPE works under Lokayukta supervision)",
    "functions": "Corruption investigations, trap cases, ombudsman inquiries",
    "officialWebsite": "https://mplokayukt.nic.in/",
    "helpline": "1064",
    "email": "Via website",
    "address": "Bhopal"
  },
  {
    "level": "State",
    "stateOrUt": "Maharashtra",
    "bodyName": "Anti-Corruption Bureau & Maharashtra Lokayukta",
    "type": "ACB + Ombudsman",
    "jurisdiction": "State officials, local bodies, PSUs (first state Lokayukta, 1971)",
    "functions": "Trap cases, investigations, ombudsman inquiries",
    "officialWebsite": "https://acbmaharashtra.gov.in/",
    "helpline": "1064 / +91 9930997700 (WhatsApp)",
    "email": "acbwebmail@mahapolice.gov.in",
    "address": "Mumbai"
  },
  {
    "level": "State",
    "stateOrUt": "Manipur",
    "bodyName": "State Vigilance & Lokayukta",
    "type": "Vigilance/Ombudsman",
    "jurisdiction": "State officials & public servants",
    "functions": "Vigilance & ombudsman functions",
    "officialWebsite": "Portal not confirmed",
    "helpline": "1064",
    "email": "Via CPGRAMS",
    "address": "Imphal"
  },
  {
    "level": "State",
    "stateOrUt": "Meghalaya",
    "bodyName": "State Vigilance & Meghalaya Lokayukta",
    "type": "Vigilance/Ombudsman",
    "jurisdiction": "State officials & public servants",
    "functions": "Anti-corruption & ombudsman functions",
    "officialWebsite": "Portal not confirmed",
    "helpline": "1064",
    "email": "Via CPGRAMS",
    "address": "Shillong"
  },
  {
    "level": "State",
    "stateOrUt": "Mizoram",
    "bodyName": "State Vigilance & Mizoram Lokayukta",
    "type": "Vigilance/Ombudsman",
    "jurisdiction": "State officials & public servants (Lokayukta Bill 2019)",
    "functions": "Vigilance & ombudsman functions",
    "officialWebsite": "Portal not confirmed",
    "helpline": "1064",
    "email": "Via CPGRAMS",
    "address": "Aizawl"
  },
  {
    "level": "State",
    "stateOrUt": "Nagaland",
    "bodyName": "Vigilance Commission & Nagaland Lokayukta",
    "type": "Vigilance/Ombudsman",
    "jurisdiction": "State officials & public servants",
    "functions": "Anti-corruption & ombudsman functions",
    "officialWebsite": "Portal not confirmed",
    "helpline": "1064",
    "email": "Via CPGRAMS",
    "address": "Kohima"
  },
  {
    "level": "State",
    "stateOrUt": "Odisha",
    "bodyName": "Odisha Vigilance & Odisha Lokayukta",
    "type": "Vigilance + Ombudsman",
    "jurisdiction": "State officials, local bodies, PSUs",
    "functions": "Corruption investigations & ombudsman inquiries",
    "officialWebsite": "https://odishavigilance.gov.in/",
    "helpline": "1064",
    "email": "Via website",
    "address": "Bhubaneswar"
  },
  {
    "level": "State",
    "stateOrUt": "Punjab",
    "bodyName": "Vigilance Bureau & Punjab Lokayukta",
    "type": "Vigilance + Ombudsman",
    "jurisdiction": "State officials & public servants",
    "functions": "Corruption investigations & ombudsman functions",
    "officialWebsite": "https://vigilancebureau.punjab.gov.in/",
    "helpline": "1800-1800-1000",
    "email": "Via website",
    "address": "Chandigarh"
  },
  {
    "level": "State",
    "stateOrUt": "Rajasthan",
    "bodyName": "Anti-Corruption Bureau & Rajasthan Lokayukta",
    "type": "ACB + Ombudsman",
    "jurisdiction": "State officials, local bodies, PSUs",
    "functions": "Trap cases, investigations, ombudsman inquiries",
    "officialWebsite": "https://acb.rajasthan.gov.in/",
    "helpline": "1064",
    "email": "Via website",
    "address": "Jaipur"
  },
  {
    "level": "State",
    "stateOrUt": "Sikkim",
    "bodyName": "State Vigilance & Sikkim Lokayukta",
    "type": "Vigilance/Ombudsman",
    "jurisdiction": "State officials & public servants",
    "functions": "Vigilance & ombudsman functions",
    "officialWebsite": "Portal not confirmed",
    "helpline": "1064",
    "email": "Via CPGRAMS",
    "address": "Gangtok"
  },
  {
    "level": "State",
    "stateOrUt": "Tamil Nadu",
    "bodyName": "Directorate of Vigilance & Anti-Corruption & TN Lokayukta",
    "type": "DVAC + Ombudsman",
    "jurisdiction": "State officials, local bodies, PSUs (Lokayukta est. 2018)",
    "functions": "Corruption investigations & ombudsman inquiries",
    "officialWebsite": "https://dvac.tn.gov.in/",
    "helpline": "1064 (anti-corruption) / 1965 (vigilance)",
    "email": "dvac@nic.in",
    "address": "Chennai"
  },
  {
    "level": "State",
    "stateOrUt": "Telangana",
    "bodyName": "Anti-Corruption Bureau & Telangana Lokayukta",
    "type": "ACB + Ombudsman",
    "jurisdiction": "State officials, local bodies, PSUs",
    "functions": "Trap cases, investigations, ombudsman inquiries",
    "officialWebsite": "https://acb.telangana.gov.in/",
    "helpline": "1064",
    "email": "Via website",
    "address": "Hyderabad"
  },
  {
    "level": "State",
    "stateOrUt": "Tripura",
    "bodyName": "State Vigilance & Tripura Lokayukta",
    "type": "Vigilance/Ombudsman",
    "jurisdiction": "State officials & public servants",
    "functions": "Vigilance & ombudsman functions",
    "officialWebsite": "Portal not confirmed",
    "helpline": "1064",
    "email": "Via CPGRAMS",
    "address": "Agartala"
  },
  {
    "level": "State",
    "stateOrUt": "Uttar Pradesh",
    "bodyName": "Vigilance Establishment & U.P. Lokayukta",
    "type": "Vigilance + Ombudsman",
    "jurisdiction": "State officials, local bodies, PSUs",
    "functions": "Corruption investigations & ombudsman inquiries",
    "officialWebsite": "https://lokayukta.up.nic.in/",
    "helpline": "1064",
    "email": "Via website",
    "address": "Lucknow"
  },
  {
    "level": "State",
    "stateOrUt": "Uttarakhand",
    "bodyName": "Vigilance Department & Lokayukta (Vacant)",
    "type": "Vigilance/Ombudsman",
    "jurisdiction": "State officials & public servants",
    "functions": "Vigilance functions & ombudsman (post currently vacant)",
    "officialWebsite": "https://vigilance.uk.gov.in/",
    "helpline": "1064",
    "email": "Via website",
    "address": "Dehradun"
  },
  {
    "level": "State",
    "stateOrUt": "West Bengal",
    "bodyName": "Vigilance Commission & WB Lokayukta",
    "type": "Vigilance/Ombudsman",
    "jurisdiction": "State officials & public servants",
    "functions": "Anti-corruption & ombudsman functions",
    "officialWebsite": "Portal not confirmed",
    "helpline": "1064",
    "email": "Via CPGRAMS",
    "address": "Kolkata"
  },
  {
    "level": "UT",
    "stateOrUt": "Delhi",
    "bodyName": "Anti-Corruption Branch (GNCTD) & Delhi Lokayukta",
    "type": "ACB + Ombudsman",
    "jurisdiction": "Delhi govt officials, local bodies, ULBs",
    "functions": "Trap cases, investigations, ombudsman inquiries",
    "officialWebsite": "https://vigilance.delhi.gov.in/ & https://lokayukta.delhi.gov.in/",
    "helpline": "1031",
    "email": "lokayukta.delhi@nic.in",
    "address": "New Delhi"
  },
  {
    "level": "UT",
    "stateOrUt": "Jammu & Kashmir",
    "bodyName": "Anti-Corruption Bureau & Vigilance (No Lokayukta)",
    "type": "ACB + Vigilance",
    "jurisdiction": "J&K govt officials & public servants",
    "functions": "Corruption investigations (No Lokayukta yet)",
    "officialWebsite": "Portal not confirmed",
    "helpline": "1064",
    "email": "Via CPGRAMS",
    "address": "Srinagar/Jammu"
  },
  {
    "level": "UT",
    "stateOrUt": "Ladakh",
    "bodyName": "Vigilance (No dedicated anti-corruption agency)",
    "type": "Vigilance",
    "jurisdiction": "Limited local vigilance setup",
    "functions": "Refer to CVC/CBI for major cases",
    "officialWebsite": "Via CPGRAMS",
    "helpline": "Contact CVC 1800110180",
    "email": "Via portal",
    "address": "Leh"
  },
  {
    "level": "UT",
    "stateOrUt": "Chandigarh",
    "bodyName": "UT Vigilance Department (No dedicated ACB)",
    "type": "Vigilance",
    "jurisdiction": "Chandigarh admin & officials",
    "functions": "Vigilance oversight (use CVC/CBI for major cases)",
    "officialWebsite": "Via CPGRAMS",
    "helpline": "1064",
    "email": "Via CPGRAMS",
    "address": "Chandigarh"
  },
  {
    "level": "UT",
    "stateOrUt": "Puducherry",
    "bodyName": "Vigilance (No Lokayukta)",
    "type": "Vigilance",
    "jurisdiction": "Puducherry govt officials",
    "functions": "Vigilance functions (No Lokayukta yet)",
    "officialWebsite": "Portal not confirmed",
    "helpline": "1064",
    "email": "Via CPGRAMS",
    "address": "Puducherry"
  },
  {
    "level": "UT",
    "stateOrUt": "Andaman & Nicobar",
    "bodyName": "Departmental Vigilance only",
    "type": "Vigilance",
    "jurisdiction": "Limited local vigilance",
    "functions": "Use CVC/CBI/CPGRAMS for complaints",
    "officialWebsite": "Via CPGRAMS",
    "helpline": "Contact CVC 1800110180",
    "email": "Via portal",
    "address": "Port Blair"
  },
  {
    "level": "UT",
    "stateOrUt": "Lakshadweep",
    "bodyName": "Departmental Vigilance only",
    "type": "Vigilance",
    "jurisdiction": "Limited local vigilance",
    "functions": "Use CVC/CBI/CPGRAMS for complaints",
    "officialWebsite": "Via CPGRAMS",
    "helpline": "Contact CVC 1800110180",
    "email": "Via portal",
    "address": "Kavaratti"
  },
  {
    "level": "UT",
    "stateOrUt": "Dadra & Nagar Haveli, Daman & Diu",
    "bodyName": "Departmental Vigilance only",
    "type": "Vigilance",
    "jurisdiction": "Limited local vigilance",
    "functions": "Use CVC/CBI/CPGRAMS for complaints",
    "officialWebsite": "Via CPGRAMS",
    "helpline": "Contact CVC 1800110180",
    "email": "Via portal",
    "address": "Silvassa/Daman"
  }
];
